### ISSUE TITLE
有时一条消息会被收到多次

### ISSUE THREAD

**Issue by cnjsstong2** [leancloud/js-realtime-sdk#104]
经测试，当某些情况发生（如网络状况不良等，无法100%复现）时，会发生同时有多个websocket链接in progress的情况。这个时候，当其它peer发来一条消息，本地的message事件会被调用多次。感觉像是connection被错误的判断为close，所以重新链接了？

**Comment by wangxiao** [comment]
我这边没法复现这个问题，但是从代码上面看，确实是有可能产生两个 websocket 实例，已经做了修正，不知道会不会解决这个问题。
https://github.com/leancloud/js-realtime-sdk/pull/105
