### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by qbaty** [leancloud/js-realtime-sdk#11]
<pre>
var rtObject = lc.realtime({
   // appId 需要换成你自己的 appId
   appId: '9p6hyhh60av3ukkni3i9z53q1l8yy3cijj6sie3cewft18vm',
   // clientId 是自定义的名字，当前客户端可以理解的名字
   clientId: 'abc123'
   // auth 是权限校验的服务器地址，具体请看文档
   // auth: 'http://signature-example.avosapps.com/sign'
});
var room = rt.room('sasfalklkjdlfs123');
</pre>

rt 是什么？

**Comment by qbaty** [comment]
还是没有获取用户有多少room 的 Api 么？难道还得手动去查 AVOSRealtimeGroups Class

**Comment by wangxiao** [comment]
您好，感谢使用 LeanCloud 产品。第一个问题，是修改时的错误，rt 就是指 rtObject，已经修正。
获取用户有多少 room 的 API 确实暂时还没有，确实有必要，我尽快支持下。
https://github.com/leancloud/js-realtime-sdk/pull/12

**Comment by wangxiao** [comment]
您好，已经增加相关接口。

获取用户有多少 Room 就是  realtimeObject.query() 稍后补充文档。
https://github.com/leancloud/js-realtime-sdk/pull/14
