### ISSUE TITLE
断开重连之后 message 会收到两条一样的消息

### ISSUE THREAD

**Issue by wangxiao** [leancloud/js-realtime-sdk#117]

**Comment by wangxiao** [comment]
未能复现。

**Comment by pianfeng240** [comment]
real-time 版本 2.0.6
问题1： 聊天双方都超时，一方发送的消息，另一方收到两条，可以稳定重现
问题2： 本地超时重练，发送消息，成功，但本地realtimeobj 的 message事件收到自己发送的消息，可以稳定重现
![qq20150806-1](https://cloud.githubusercontent.com/assets/11719252/9108330/ecd225ca-3c5f-11e5-9ceb-d62a4ddfe970.png)

**Comment by leeyeh** [comment]
@pianfeng240 请问你是不是在 `realtimeObject.on('open', callback)` 的 callback 中绑定的接收消息事件。

**Comment by pianfeng240** [comment]
不是。
我解决这个问题了，createSocket的时候需要判断下将监听的事件先取消

**Comment by leeyeh** [comment]
解决就好，多问一句，那你是在什么时候绑定的「收到消息」的事件的呢？你说的「createSocket的时候」是指 `reuse` 事件吗？

**Comment by pianfeng240** [comment]
对象初始化之后 绑定事件 
_realTimeObj.on('message', function(data) { .. }；
_realTimeObj.on('open', function() {...}

是的，reuse事件
