### ISSUE TITLE
应该提供 rt.clientId ，现在似乎只能用 rt.cache.options.peerId

### ISSUE THREAD

**Issue by lzwjava** [leancloud/js-realtime-sdk#124]
后面需要判断一个 room 是否包含自己的逻辑。希望 rt 能方便读取 clientId 变量。这样就不用自己维护了。

@wangxiao

**Comment by wangxiao** [comment]
恩，确实可以存储一下。

**Comment by wangxiao** [comment]
https://github.com/leancloud/js-realtime-sdk/pull/131
