### ISSUE TITLE
send message 回调中的data 不应该是ack 命令

### ISSUE THREAD

**Issue by lzwjava** [leancloud/js-realtime-sdk#126]
现在的是 ack：

![image](https://cloud.githubusercontent.com/assets/5022872/8577062/d51aab3e-25d8-11e5-8252-93be173b8713.png)

```
    room.send({
        text: val
    }, {
        type: 'text'
    }, function (data) {

        // 发送成功之后的回调
        inputSend.value = '';
        showMsg(data);
        printWall.scrollTop = printWall.scrollHeight;
    });
```

上面 data 回调是 message 较好，这样可以统一处理，android 和 iOS 都是回调的 message。

@wangxiao

**Comment by wangxiao** [comment]
什么意思？回调想要什么结果？

**Comment by lzwjava** [comment]
我想要的是那个message。想发送完回调 的data 跟我log拉取历史消息的 是一样的。有 timestamp、fromPeerId、msg.type 等属性。现在我是自己构造了一个 message 来统一处理(因为回调给我的是 ack 命令)，

```js
    room.send({
        text: val
    }, {
        type: 'text'
    }, function (data) {

        // 发送成功之后的回调
        inputSend.value = '';
        data.msg = {};
        data.timestamp = new Date();
        data.msg.type = 'text';
        data.msg.text = val;
        data.fromPeerId = rt.cache.options.peerId;
        showMsg(data);
        printWall.scrollTop = printWall.scrollHeight;
    });
```

https://github.com/leancloud/leanchat-cloudcode/blob/master/webapp/app/scripts/test.js#L337-L352

**Comment by wangxiao** [comment]
理解你的意思了，就是现在回调的 data 是不统一 的，确实有可能。
另外，代码中不要使用 cache 中的值。
