### ISSUE TITLE
应当始终抛出 Error 实例，而非字符串

### ISSUE THREAD

**Issue by leeyeh** [leancloud/js-realtime-sdk#128]
SDK 对用户抛出的异常应当尽可能清晰地传达出发生的错误信息，现在有两点问题。

#### 抛出的是字符串

抛出具体的 Error 实例会显示具体的 Error 类型，并附上调用堆栈，可以帮助用户更快地理解到底发什么了什么。两者区别如下图：

```javascript
{
    ping: function() {
        // ...
        throw('Must call after open() has successed.');
    },
    room: function() {
        // ...
        throw new Error('Must call after open() has successed.');
    }
}
```

![](http://cl.ly/btrL/64350AE7-2AC9-4F80-8B5D-885E97FF1E4C.png)

参考浏览器内建的几个 Error 类：https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#Error_types

#### Error 信息太随意

Error 信息应该包含「发什么了什么错误」，可以给出「可能的原因及解决方案」。比如上面的 case 的错误文案可以更具体：「RealtimeObject.ping() called before the RealtimeObject.open() succeeded. RealtimeObject.ping() should be called in the callback of AV.realtime() or in a handler of  'open' event of RealtimeObject, see https://github.com/leancloud/js-realtime-sdk/blob/master/demo/demo1/test.js .」，这样可能对用户更有价值。

**Comment by wangxiao** [comment]
恩，error 这个确实做的还不够细致，可以考虑和这个 [issue](https://github.com/leancloud/js-realtime-sdk/issues/110) 一起搞下。

**Comment by leeyeh** [comment]
fixed in v3
