### ISSUE TITLE
RoomObject.receive RoomObject.receipt 应采用事件模型而非方法

### ISSUE THREAD

**Issue by leeyeh** [leancloud/js-realtime-sdk#129]
这两个方法容易产生误解，考虑 RoomObject 是否也应该有个事件机制：`room.on('message', callback);` 或者至少方法名不要用动词：`room.onMessage(callback)`。

**Comment by wangxiao** [comment]
当时设计时考虑 roomObject 中不要暴露底层事件，不希望用户产生混乱。
receive 和 receipt 相当于是快捷方法。

**Comment by wangxiao** [comment]
已经讨论。
