### ISSUE TITLE
是否会支持跟leanmessage-javascript-sdk类似的getStatus或watch机制？

### ISSUE THREAD

**Issue by cnjsstong2** [leancloud/js-realtime-sdk#13]
目前的js-realtime-sdk中貌似还没有办法获取其它client的状态，也没有办法监测上下线事件？后续是否有支持的打算？大约是什么时间能有sdk更新？

PS.
js-realtime-sdk是否可以认为是重构的leanmessage-javascript-sdk？还是这两者各有侧重？

**Comment by wangxiao** [comment]
你好，感谢使用 LeanCloud 产品。

我们在第二版中简化了逻辑概念，并且去掉了「获取其他 client 的状态」这种功能，
因为之前会照成大量的垃圾信息。（这也是微信没有在线状态的原因。）
但是您自己肯定是可以实现的，只需要像这个 room 中发送自定义的一个特殊的事件信息即可。

这个 js-realtime-sdk 是吸取之前的经验重新实现的新版，日后会只维护该版本。
