### ISSUE TITLE
全局事件有些诡异

### ISSUE THREAD

**Issue by leeyeh** [leancloud/js-realtime-sdk#130]
[文档](https://leancloud.cn/docs/js_realtime.html#全局事件)里的事件其实是 RealtimeObject 实例内部派发的事件，RealtimeObject 是多例的，这里称全局事件是不是不妥。

另外 RealtimeObject 与 RoomObject 是 1:n 的关系，`create`, `join`, `left`, `message`, `receipt` 这几个事件都是 Room 相关的，都归 RealtimeObject 管了造成了概念上造成混乱（`rt.on('create', cb)` 怎么看都是订阅的 rt 创建事件吧）与代码上的耦合（现在是在 Room 内部直接操作 RealtimeObject 的事件中心）。

**Comment by wangxiao** [comment]
「全局事件」比较直观，或者有什么好名字？

事件在底层派发出来，我反而觉得比较统一、不混乱，那你有什么建议？

**Comment by wangxiao** [comment]
已经讨论。
