### ISSUE TITLE
去掉 encodeHTML 自动转义选项

### ISSUE THREAD

**Issue by leeyeh** [leancloud/js-realtime-sdk#133]
现在的自动转义的问题是：SDK 不知道要转哪些字段，用户不知道 SDK 转了哪些字段。

目前对两个字段进行了转义：

- 普通消息中的不是合法 JSON 字符串的 message.data
- 富媒体消息类型中的 text 字段

根据[文档](https://leancloud.cn/docs/realtime_v2.html#消息_Message_)，消息的 data 可以是任意合法的 JSON，这里无法判断哪些字段是「用户输入直接输出到界面上的」，对于我们定义好的富媒体消息类型的`_lcfile.metaData.name`字段、用户自定义 JSON 作为 data 的内容，都是有 XSS 风险的，这些还是需要用户手动转义。如果我们无法保证 100% 的安全，那还不如什么都不做。

此外，我们现在的 HTML 转义「考虑到其中有可能是 JSON，所以不做 HTML 强过滤，仅对标签过滤」，所以没有转义`"`，安全这个事情不是 1 就是 0，这转义本身也形同虚设啊。

除开可行性，我认为 HTML 转义这件事应该是在最终环节进行的（换句话说谁往页面上写 HTML 谁负责转义），我们的 SDK 并不关心 View 层，所以不应该有转义的功能。

**Comment by sunng87** [comment]
+1
#54

**Comment by wangxiao** [comment]
非常担心用户没有这个意识，要是去掉配置项，那就开放 tool 中的 encodeHTML 方法，并且在文档中注明。

**Comment by leeyeh** [comment]
我们就别替用户操这个心了吧。这种事情交给更专业的工具去做吧（比如各种模板引擎），我们实时通信 SDK 就别提供这种方法了吧。文档、demo
肯定是要强调的，写些文章也可以。

2015-07-16 18:05 GMT+08:00 尼奥 <notifications@github.com>:

**Comment by wangxiao** [comment]
情况是确实有用户只在有 jQuery 的情况下使用，并没有做防御 XSS 的意识，所以最好还是能替用户做就替用户做。我理解的接口设计原则还是应该简单，内部功能强大，能替用户做的事情，就不让用户自己再考虑。所以还是想至少暴露出来一个能够使用的转义方法。

**Comment by leeyeh** [comment]
我们的 js SDK 提供的是实时通信的功能，可以在浏览器、node、react-native（理想中）等环境运行，提供 html
转义的工具方法会让这个模块职责不单一。我们也没有希望用户仅仅使用我们的 SDK 就能完成应用的开发，新手友好如 jQuery 都没有
escapeHTML 方法，我们一个数据层的 SDK 提供这个方法干什么。

在 2015年7月17日 下午4:26，尼奥 <notifications@github.com>写道：

**Comment by wangxiao** [comment]
好，确实有点尴尬。
考虑到面向未来，我同意去掉这个功能。

**Comment by wangxiao** [comment]
已在文档中去掉，代码中可以留着。
https://github.com/leancloud/docs/pull/862
