### ISSUE TITLE
join 与 member-join 事件分开

### ISSUE THREAD

**Issue by leeyeh** [leancloud/js-realtime-sdk#136]
协议层[文档](https://github.com/leancloud/avoscloud-push/blob/master/push-server/doc/protocol.md#创建对话)中 join 与 member-join 事件的意义是不同的，现在在 SDK 层抹平为 join 了，用户还要自己区分。同理还有 left。

iOS 与 Android 的 SDK 对这四个事件的命名是`invited`，`kicked`，`membersjoined`，`membersleft`。应该统一。

**Comment by wangxiao** [comment]
可以。如果名字不会冲突，原来的也暴露着吧。
