### ISSUE TITLE
无法使用US区域？

### ISSUE THREAD

**Issue by cnjsstong2** [leancloud/js-realtime-sdk#142]
在创建realtime时指定`region: 'us'`，出现DNS无法解析的错误：
http://router-a0-push.leancloud.cn/v1/route?_t=1438282361213&appId=＊＊＊＊＊&secure=1

**Comment by wangxiao** [comment]
@sunng87 宁姐，是这个节点么？

**Comment by sunng87** [comment]
嗯，这个新域名有一些问题，我们尽快处理一下

**Comment by sunng87** [comment]
你好，域名问题已经解决，请重试一下

**Comment by cnjsstong2** [comment]
可以了，谢谢！ @sunng87 @wangxiao
