### ISSUE TITLE
refactor EventCenter, Engine and cache

### ISSUE THREAD

**Issue by leeyeh** [leancloud/js-realtime-sdk#143]
要解决的问题

1. 所有的实例都是原始 Object 类的实例，不够面向对象，用户使用、开发者调试起来很费劲
2. 事件中心模式使得所有的内部调用都解耦了，几乎所有的方法都被代理到 Engine 这个命名空间上，然后通过事件中心调用，代码梳理起来很费劲
3. 方法的参数（依赖）不明确，无法单测（所有的方法都需要传参数 cache，所有的引用都存在 cache 里，有全局变量的嫌疑）
4. cache 中的几个 flag 对程序状态的影响不清晰。

方案

1. 增加类 RealtimeConnection（原 RealtimeObject）、Conversation、Message 以及 Message 的富媒体子类。
2. 移除 EventCenter 与 Engine。RealtimeConnection、Conversation 继承自 EventEmitter。RealtimeConnection - WebSocket、RealtimeConnection - Conversation 之间直接调用方法、监听事件。Engine 上的静态方法改为 RealtimeConnection、Conversation、Message 的实例方法。
3. 使用有限状态机代替 flag。

**Comment by wangxiao** [comment]
这个改动其实基本算是完全的重写，我们需要再讨论下。

**Comment by leeyeh** [comment]
好的，直接在这里讨论吧。

**Comment by wangxiao** [comment]
这个改动比较多，需要的讨论也较多，可以你考虑好之后直接找我讨论。
在此可以回复我的几个问题：
* 重构后从 SDK 的使用者层面考虑，预期收益是什么？
* 重构后从代码层面考虑，预期收益是什么？
* 目前代码中存在的最首要的问题是什么，推动你这样改动？

**Comment by leeyeh** [comment]
> 重构后从 SDK 的使用者层面考虑，预期收益是什么？
- 一些 issue 需要依赖上述的某些改动。比如：`AV.realtime(options, callback);`这个方法中的 callback 回调是没有参数的，用户没有办法在回调中拿到 realtimeObject 实例，而这个问题与 1、2 都有关系。
- 使用类代替 map 能降低用户的理解成本，比如收到的 Message 的类型等应该由 SDK 来封装，而且那样用户在控制台或者 tracelog 中也能看到真实的类名而不是 Object。
- 某些设计模式可以避免某些问题的出现，比如有限状态机模型可以避免 #140 这种问题。
