### ISSUE TITLE
在 readme.md 中补充贡献代码的指南

### ISSUE THREAD

**Issue by wangxiao** [leancloud/js-realtime-sdk#144]
因为又引入了新的构建系统，如果有人想要查看代码或者贡献代码，成本相当于提高了。所以需要补充这些步骤、相关依赖和目录结构说明，以助于用户帮助贡献代码。

**Comment by sunng87** [comment]
可以放到 CONTRIBUTING.md 里

**Comment by wangxiao** [comment]
最好还是进到 GitHub 的这个 Repo 中直接能够看到的，还是 README.md 里面更好些。
