### ISSUE TITLE
[待定] 聊天记录的缓存

### ISSUE THREAD

**Issue by wangxiao** [leancloud/js-realtime-sdk#145]
因为有用户提出，所以记录在此，感觉 Web 端缓存的必要性还有待考虑。

主要是：
- Web 端网络状况一般较好，用户也都习惯刷新；
- 最主要的是 Web 端很少有用户考虑流量大小；

后续看是否有较多用户提出，再考虑实现。

**Comment by xgzl87** [comment]
现在有cordova等html app的，所以还是有必要的，呵呵
