### ISSUE TITLE
js sdk 不支持在线人数查询么？

### ISSUE THREAD

**Issue by mouse-lin** [leancloud/js-realtime-sdk#149]

**Comment by leeyeh** [comment]
可以先通过  [`roomObject.list()`](https://leancloud.cn/docs/js_realtime.html#RoomObject_list) 获得成员列表，然后再批量 [`roomObject.ping()`](https://leancloud.cn/docs/js_realtime.html#RealtimeObject_ping) 一下。如果是暂态对话则不支持。

**Comment by mouse-lin** [comment]
@leeyeh 
roomObject.ping() 每次不是只可以20个么？
我原本是打算通过 REST API 的 https://leancloud.cn/1.1/rtm/transient_group/onlines?gid=xxx 去获取的，但是不知道为什么一直返回的是0

**Comment by sunng87** [comment]
@mouse-lin 这个接口只能查询聊天室的在线人数

**Comment by mouse-lin** [comment]
@sunng87 那请问下在线人数有办法获取么？

**Comment by wangxiao** [comment]
@mouse-lin 目前还没有，@sunng87 可以考虑包装一下。

**Comment by mouse-lin** [comment]
@wangxiao 请问下什么时候可以好呢？

**Comment by wangxiao** [comment]
目前没办法给出明确时间，可以通过 list() 和 ping() 方法组合来获取，客户端消耗并不大，因为都是通过 WebSocket 而不是 http 请求。

**Comment by mouse-lin** [comment]
@wanggc 可以通过 list() 与 ping() 方式批量来获取用户在线数量，但是用户关闭页面后，好像是没有触发的条件， left event，是要主动触发的？

**Comment by wangxiao** [comment]
恩，完全离线不是一个很精准的实时（因为可能是网络不好），你可以手动触发 realtimeObject.close();
