### ISSUE TITLE
WebSocket opening handshake was canceled错误

### ISSUE THREAD

**Issue by cnjsstong2** [leancloud/js-realtime-sdk#150]
感觉是今天刚刚出现的问题。在Android 5.0 Chrome上，无法建立websocket链接，提示WebSocket opening handshake was canceled。在Android 5.1模拟器上，显示以下警告：

![qq 20150828015533](https://cloud.githubusercontent.com/assets/4534745/9540093/792d9620-4d28-11e5-9310-771a5fad9757.png)
![qq 20150828015605](https://cloud.githubusercontent.com/assets/4534745/9540097/7be4689e-4d28-11e5-81dc-18c3ab14e0e3.jpg)
![qq 20150828020025](https://cloud.githubusercontent.com/assets/4534745/9540103/96b6dd32-4d28-11e5-8733-93bb4406d138.jpg)
![qq 20150828020042](https://cloud.githubusercontent.com/assets/4534745/9540105/99f28546-4d28-11e5-8ca0-d0248b4567f7.jpg)

使用的是2.2.1版本，连接us region。

**Comment by cnjsstong2** [comment]
做了一些research，感觉跟SHA-1被sunset有关。http://googleonlinesecurity.blogspot.com/2014/09/gradually-sunsetting-sha-1.html 建议server端换用其它加密算法的证书。

**Comment by cnjsstong2** [comment]
Chrome版本为44

**Comment by leeyeh** [comment]
cc @sunng87

**Comment by sunng87** [comment]
收到，我们确认一下

**Comment by kadashu** [comment]
这个能稳定重现吗？
因为我们服务端没有变更，有问题的话，按理不应该今天才出现。另外，我们在Chrome（v44, Androd 5.0 ）上打开了 http://api.leancloud.cn/1/ping，没有发现证书有问题。

怀疑是与网络有关系，请在wifi环境里确认一下。

**Comment by cnjsstong2** [comment]
也可能是之前没有注意到，目测只有wss链接建立时会有问题，https没有测试过，今天试试看。目前100%重现。

**Comment by cnjsstong2** [comment]
目前非Android的部分桌面版Chrome也出现了同样的问题。猜想是在新版本chrome内核中对secure websocket处理的部分做了更新，不接受SHA-1加密的证书。事实上，*.leancloud.cn这个wildcard certificate有问题的只有root CA那一层（GeoTrust，SHA-1），后面的intermediate CA以及证书本身并没有问题。

**建议的解决方案：**
**尽快更新成不包含任何SHA-1加密的证书。**

否则目前的状况下JavaScript实时通信基本没有可用性啊………………ToT
谢谢！

**Comment by wangxiao** [comment]
你好，Android 上面可以先通过关闭 wss 协议，走简单的 ws 方式先实现可用。
具体方法是实例化时，secure 设置为 false，
参考 Demo http://leancloud.github.io/js-realtime-sdk/demo/demo2/

**Comment by cnjsstong2** [comment]
谢谢，确实是可以的。但是聊天消息非加密传输总不是个好办法……希望能尽快解决！

**Comment by wangxiao** [comment]
恩，是的，我们这边得研究下。

**Comment by kadashu** [comment]
你好，请告之下桌面版本chrome的版本号，我们方便测试。
如你所说，我们确认了证书的问题，上周五有生成基本的网站证书，因为别的事情，还没来得及测试。

**Comment by wangxiao** [comment]
也麻烦 @cnjsstong2 有时间帮忙一起测试一下，非常感谢。

**Comment by cnjsstong2** [comment]
@kadashu 是Mac OS X 10.10.2, Chrome v44.0.2403.155 (64-bit)

另外，可以参考https://shaaaaaaaaaaaaa.com/上关于GeoTrust的描述。

**Comment by sunng87** [comment]
@cnjsstong2 我们刚刚更新了美国环境的 SSL 实现，不知现在还能否重现？

**Comment by cnjsstong2** [comment]
@sunng87 好的，我明天上班时测试一下。非常感谢。

**Comment by cnjsstong2** [comment]
@sunng87 看起来没问题了。辛苦了。

**Comment by sunng87** [comment]
@cnjsstong2 看来是 JDK 的 ssl 实现的bug，谢谢报告。我们之后会在中国的部署也更新。
