### ISSUE TITLE
获取当前用户所有 conversation 操作发出的请求达到了限制

### ISSUE THREAD

**Issue by leeyeh** [leancloud/js-realtime-sdk#151]
目前 `realtimeObject.query()` 返回的是一个 array of Object，用户需要手动依次调用 `realtimeObject.conv(cid)` 来实例化 Conversation，在这个过程中每次调用 `conv()` 方法都会发出一个请求，很容易达到后端的限制。

理想中，`query()` 方法应该直接返回 Conversation 的实例数组，这要求我们抽象出一个 Conversation 类。现在作为临时方案，可以先把 `conv(id)` 中校验对话是否存在这一步去掉，直接返回 Conversation 实例。

https://ticket.leancloud.cn/tickets/8247

**Comment by leeyeh** [comment]
现在希望 conv() 方法默认不发请求，直接返回 Conversation 实例，但是现在 conv() 方法是唯一返回 Conversation 实例的 api，所以还是需要有一种方法能够通过 cid 拿到服务端会话的信息。我想到的有以下几种方案：

1. 给 Conversation 上增加一个 updateFromServer() 的 api 用来补完自身的信息。这个的问题是其本质是通过 realtimeObject.query() 来做的，绕了一大圈，且 Conversation 需要持有 realtimeObject 的实例。
2. 给 conv() 增加一个参数。这个 API 会变得更复杂，现在把「创建会话」与「查询某个会话」揉成一个 API 就已经很诡异了。
3. 查询某个会话（通过 cid 拿到服务端会话的信息）交回给 query() 来做，然后 query() 返回 Conversation 实例。比较彻底，改动最大，API 不向前兼容。

总之，在现在的架构下我想不到什么好的解决方案。 @wangxiao

**Comment by wangxiao** [comment]
创建 Room 时要查询一次这个 Room 在服务器端是否存在，是因为之前有过问题，用户传了很多他们已经删除了的 id 创建 RoomObject 。

* 我觉得目前服务端每分钟 30 次限制确实有点严格，每分钟 30 次，听起来都不像是 Socket，像 Http 轮训；
* 查询交给 Query 也还是解决不了限制的问题，用户仍然会去 Query 所有的 Room；
* 确实可以去掉创建时的那次 Query，就是无法保证这个 id 在服务端一定存在，但是可行；
* 收发任何消息倒是可以退回到使用 RealtimeObj.on 方法，SDK 没有改动，但是用户改动较大；

目前同意去掉那次 query 。

**Comment by leeyeh** [comment]
现在的问题不是「是否要去掉那次 query」，而是「去掉 conv(id) 的 query 之后没有办法获得一个对话的详细信息了」。

在 2015年8月31日 上午4:57，尼奥 <notifications@github.com>写道：

**Comment by wangxiao** [comment]
这种情况就通过 query 吧，创建的时候不绑定了，不然目前没有办法解决请求次数限制的问题，最好还是应该放宽请求限制，每分钟仅 30 次，太少了。。。

**Comment by leeyeh** [comment]
问题没有表达清楚，下面详细解释一下：

但是现在的 query() 不会返回 Conversation 实例啊，现在的用法就是 `rt.query()` 拿到一批
conversationId，然后遍历调用 `rt.conv(id)`，如果去掉了 `rt.conv(id)`
内部调用的 `rt.query()` 那么返回的 Conversation 实例是没有 name、members 等信息的。

在 2015年8月31日 上午11:03，尼奥 <notifications@github.com>写道：

**Comment by wangxiao** [comment]
对，我就是这个意思。。。既然去掉 query，只能这样了。

**Comment by sunng87** [comment]
有没有可能去掉 conv(id) 的这个调用就可以发消息，也就是用户 query 出一批 conversation 之后不需要在逐个调用 conv() 去获取具体信息，只在必要的时候才获取。而且目前的 query 本身其实是会返回 conversation 所有的信息的，SDK 完全可以把这部分信息放到 coonversation 对象里。

从协议层面只要有 convid 就可以发消息，如果是一个非法的 convid，会在发送消息之后收到报错。

每分钟30次是指客户端主动发起的调用，不包括接收消息（被动触发的 ack 也不计算在内），对长连接应用正常情况下应该够用了。

**Comment by wangxiao** [comment]
好的。（不过分钟级别 30 次，确实不是一个很大的数字，正常程序很容易达到。。。

感觉目前去掉创建时内部的 query 也没啥用，因为用户可能会在外面自己再 query 一次，治标不治本。只能告知一下用户，最好不要一次性的生成所有的 roomObject，而是有一个，生成一个。

**Comment by jwfing** [comment]
既然如此，从 js sdk 层面来讲，应该是调用 conv(id) 的时候不进行网络请求才对——每一层都应该尽量减少网络请求，复用现有的信息为好。

**Comment by leeyeh** [comment]
我觉得最自然也最彻底的方案是「查询某个会话（通过 cid 拿到服务端会话的信息）交回给 query() 来做，然后 query() 直接返回 Conversation 实例」，事实上其他平台的 SDK 也是这样的。

**Comment by wangxiao** [comment]
因为目前服务端有了限制，所以改成这个方案我能够接受。

这个也是第一版时的方案，当时修改为现方案的原因：

如果直接返回 Conversation 实例，无法确定服务器端是否真的存在这个 Conversation，也无法获取 Conversation 上的默认属性，相当于用户需要手工再 query 一次，发现很多用户这样做，所以就改为替用户内部做了。

如果修改，确认下风险，还有就是最好也能听下用户的意见，因为早期版本找了一些测试用户，这也是他们提出过的优化。
