### ISSUE TITLE
members-joined以及joined

### ISSUE THREAD

**Issue by otarim** [leancloud/js-realtime-sdk#152]
js-sdk中join事件返回的op属性有'members-joined'，‘joined’这两个状态，请问这两个状态有什么区别，或者可以给下文档说明返回的data中的参数都表示些什么，谢谢。

**Comment by leeyeh** [comment]
`members-joined` 是**任何人**加入了你所在的会话，`joined` 是你（主动或被动的）加入了某个会话。

**Comment by otarim** [comment]
@leeyeh 返回字段的m以及initBy属性分别表示什么？

**Comment by leeyeh** [comment]
后续 sdk 中，这两个事件会分开。

m 是指加入对话的 clientId 列表（members-joined 事件才有）
initBy 指这个动作由谁发起（把用户加入对话的人）

后续 sdk 中会换成跟有意义的 key。
