### ISSUE TITLE
聊天历史记录获取

### ISSUE THREAD

**Issue by otarim** [leancloud/js-realtime-sdk#153]
请问有没有方法获取从A时间 —— B时间的聊天记录？

**Comment by leeyeh** [comment]
你好，我们的 github issue 只接受 bug 反馈与 feature request，相关的问题可以在我们的 [论坛](https://forum.leancloud.cn/t/topic/2455) 上讨论。

过去历史记录 API 不支持按照时间查询，因为可能查到的结果数量是不可预估的，你可以参考这个 [帖子](https://forum.leancloud.cn/t/topic/2455) 的做法实现翻页获取来完成「获取一段时间内的记录」。
