### ISSUE TITLE
2.3.0是否会影响原有版本的功能？

### ISSUE THREAD

**Issue by liuyanghejerry** [leancloud/js-realtime-sdk#159]
增加 invited, kicked, membersjoined, membersleft 事件，废弃 join, left 事件

以上是2.3.0的release notes的feature。

我想知道join和left被“废弃”的具体意思。这两个事件在这个版本里还会发生吗？

https://leancloud.cn/docs/js_realtime.html#join 而文档里并没有提到废弃。

**Comment by leeyeh** [comment]
这两个事件在 2.3.x 版本是是有的，但是不建议使用，并且会在下一个版本中彻底移除。

文档确实过时了，马上更新，谢谢反馈。

**Comment by liuyanghejerry** [comment]
OK，明白了
