### ISSUE TITLE
node js 安裝  leancloud-realtime 錯誤

### ISSUE THREAD

**Issue by wahengchang** [leancloud/js-realtime-sdk#167]
需要幫忙，

npm install leancloud-realtime --save

npm ERR! Darwin 14.1.1
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "leancloud-realtime" "--save"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
npm ERR! code ENOSELF

npm ERR! Refusing to install leancloud-realtime as a dependency of itself

謝謝你lo

**Comment by leeyeh** [comment]
我试了没有问题，请使用下面这个命令，并将执行结果贴一下，谢谢。
```
npm install leancloud-realtime --save --verb
```

**Comment by leeyeh** [comment]
你是不是试图在一个叫 leancloud-realtime 的项目里安装 leancloud-realtime ？

**Comment by wangxiao** [comment]
没有后续反馈，暂时关闭了。
