### ISSUE TITLE
复用 websocket

### ISSUE THREAD

**Issue by wangxiao** [leancloud/js-realtime-sdk#182]
js push sdk 与 js realtime 可以使用同一个 websocket 链接。

**Comment by sunng87** [comment]
我刚想提。。。可以考虑直接在 realtime 里支持 push 相关的接收功能

**Comment by wangxiao** [comment]
==# 还是。。。不耦合了。。。有种拉菲里面掺雪碧的感觉。

**Comment by leeyeh** [comment]
我觉得 push 就是 realtime 的一种用法而已，现在这两个 sdk 的代码很大部分都是一样的。

**Comment by wangxiao** [comment]
共用的部分肯定都是有，但是毕竟耦合一起会增加判断，会有耦合，我还是倾向于清晰独立的维护方式。当然，绝对共用的部分，可以提出来做成模块，各自引用。

**Comment by sunng87** [comment]
如果不放在一起的话，就要考虑在同时使用两个 sdk 的时候共享 websocket 了，我觉得也可以，看前端实现的难度了。主要就是避免两个一起用的时候，连接数乘2。。。

**Comment by wangxiao** [comment]
共享 websocket 会容易很多，不过，当初确实没想到会有共用的。

**Comment by sunng87** [comment]
没问题，最好对用户透明

**Comment by wangxiao** [comment]
恩，目前看肯定是透明的，没什么问题，要不我这就改下吧。

**Comment by leeyeh** [comment]
其实吧，对于浏览器端，多 tab 复用连接才是难点。

**Comment by wangxiao** [comment]
一下子勾起当年的回忆，做百度 Hi 时候考虑了跨浏览器通信，不过用的是 Flash 实现的一台机器一个链接。不过倒是可以试试用 post message 做多 tab 复用，肯定是可以试的，但是感觉收益很小，这么用的场景太少了。

**Comment by wangxiao** [comment]
我先把 push 和 realtime 共用 websocket 改了，别的可以看情况。

**Comment by sunng87** [comment]
之前我发现在手机的浏览器上，在后台的 tab 在一小段时间之后连 setInterval 那种定时器都会停掉，感觉很难处理。

**Comment by wangxiao** [comment]
对，手机浏览器是会停掉的。正好一个好友，写过篇博客，能够解决这个问题。https://imququ.com/post/ios-none-freeze-timer.html

**Comment by leeyeh** [comment]
不慌改，先说说方案吧。另外我还是想不出来大量同时使用 push 接收端与 realtime 的例子。

**Comment by wangxiao** [comment]
😂主要是元旦时，统计发现大量这么用的，既用了 js push 的收推送功能，又用了 js realtime 。

**Comment by leeyeh** [comment]
用户是什么具体需求呢，有用户这么用了不代表就是合理的。而且之后改成按照连接数收费那这种方案成本就应该是用户自己负责了。

**Comment by wangxiao** [comment]
因为用户具体怎么用没有太好的办法管理，但如果连接能够复用，对整体的资源消耗是会减少的，相当于服务器需要维持的长连接少了。

**Comment by jwfing** [comment]
按连接收费的方案，对于 push 带来的连接，我们还是不收费的，只对 realtime 的部分收费。

**Comment by wangxiao** [comment]
在这个 PR 中修改 https://github.com/leancloud/js-realtime-sdk/pull/186 。
