### ISSUE TITLE
2.3.3版本当使用realtimeObj.room(roomId,callback)时，必须用户在房间里才会返回房间数据

### ISSUE THREAD

**Issue by grepug** [leancloud/js-realtime-sdk#184]
很久没用AV.realtime了，总之之前的版本不是这样的：

想要使用realtimeObj.room(roomId,callback)，必须用户的clientId在_Conversation表对应的roomId的m字段存在该用户的clientId，否则获取不到房间信息。

我看了源码，应该是这里有点问题(line:918~927)
````
  var where = options.where || {};
  //默认为包含自己的查询 {"m": peerId}
  if (!where)
    where.m = where.m || cache.options.peerId;
  // 同时查找含有数组中 id 的用户所在的 conversation
  if (typeof where.m !== 'string') {
    where.m = {
      $all: where.m
    };
  }
````
不知道是有意为之还是什么原因？总之之前的版本不是这样，我仔细看了文档也没说明必须用户在房间里才能获取房间数据（从而加入房间）。

**Comment by leeyeh** [comment]
fixed in 2.3.5

**Comment by wangxiao** [comment]
@grepug 感谢反馈。
