### ISSUE TITLE
请支持获取未读消息数量

### ISSUE THREAD

**Issue by nicecui** [leancloud/js-realtime-sdk#188]
https://forum.leancloud.cn/t/topic/4484/5

其他平台已经实现：
https://leancloud.cn/docs/realtime_guide-android.html#未读消息
https://leancloud.cn/docs/realtime_guide-ios.html#未读消息

**Comment by disoul** [comment]
+1   
表示找了半天文档找不到，只能手动对比时间戳，看了下管理界面的那个接受状态貌似是检测`ack-at`

**Comment by bugyak** [comment]
请求支持

**Comment by leeyeh** [comment]
in progress.
