### ISSUE TITLE
withLastMessages只能获取部分对话的最后一条消息

### ISSUE THREAD

**Issue by ydfzgyj** [leancloud/js-realtime-sdk#189]
是否只能在启用了2.4.0的sdk之后才能记录？希望相关文档再详细一点
另外，通过这一方法获得的消息格式和其他方法获得的也并不相同，最好可以统一起来

**Comment by leeyeh** [comment]
只有使用 2.4.0 之后的 SDK 才能**在查询的同时获取**到最后一条数据，记录不分 SDK 的版本。

消息格式近期会有改进。

**Comment by sunng87** [comment]
您好，这个最近一条消息的机制是基于缓存的，确实存在可能对于较长时间不活跃的对话无法取出最近的消息，您需要在应用层对此有所处理。感谢您的报告，我们会在文档上加以强调。
