### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by sunng87** [leancloud/js-realtime-sdk#19]
记录 review 中一些问题

- [x] 命名空间
- [x] 创建 conv 是 id 是空字符串而非 `null` 的考虑是？
- [x] log 里的 setTimeout 可以去掉
- [x] 194行是否可能有数组越界
- [x] update callback 没有使用
- [x] 处理router返回404和403 的情况
- [x] startConv /remove 等函数的签名参数被注释掉了
- [x] tool.getId 返回一个自增整数即可，不要用字符串，未来可能会改成强类型

还没看完，明天可能会继续添加一些

**Comment by wangxiao** [comment]
我改一个写一个，改好了再一起看，我会叫你的。

**Comment by wangxiao** [comment]
创建 conv 是 id 是空字符串而非 null 的考虑是？

因为 js 是弱类型，所以提前设置为空字符串，相当于人为声明下，这个变量是字符串，因为逻辑上一定会设置一个字符串 id 的。

**Comment by wangxiao** [comment]
### log 里的 setTimeout 可以去掉

因为立刻取会没有，要不服务端看看有木有好的解决办法。。。

**Comment by sunng87** [comment]
log这个正常是不存在发完立刻取的场景的，这个我觉得说明一下就可以了。目前我们应该可以保证1秒以内的延迟。

**Comment by wangxiao** [comment]
https://github.com/leancloud/js-realtime-sdk/pull/20

**Comment by sunng87** [comment]
考虑 `room` 这个名字最好和整个平台统一成 `conversation` 或者相关缩写

**Comment by wangxiao** [comment]
这个名字我也纠结很久，感觉 room 比较短也好理解，conv 缩写实在是比较难理解。

**Comment by sunng87** [comment]
和平台的整体名称对应，包括概念文档、数据库的 _Conversation 表等等，如果单独叫做 room 会增加额外的沟通和理解的成本

**Comment by sunng87** [comment]
内部接口 EventCenter 的注册事件方法叫做 `on`，解除可以叫做 `off` （现在是 remove）

**Comment by sunng87** [comment]
- [ ] conv/count 接口
- [ ] send 如果是 transient 消息不需要等待 ack 和设置回调
- [ ] 收到非 transient 的 direct 消息需要回复 ack
- [ ] 回执 rcp 支持

**Comment by sunng87** [comment]
- [ ] 似乎 event center 里的 eventList 和 eventOnceList 实现是完全一致的
- [ ] open session 的 i 参数
- [ ] 是否支持 flash socket
- [ ] wsClose 可以收集一下 websocket 的 status 和reason
- [ ] 心跳包发送了但是似乎没有检查心跳包返回的情况，一定时间没有返回心跳包应该触发连接断线的事件（session pause）
- [ ] engine.auth 缺少必要参数

**Comment by sunng87** [comment]
- [ ] `engine.convUpate` typo

**Comment by wangxiao** [comment]
https://github.com/leancloud/js-realtime-sdk/pull/23
