### ISSUE TITLE
对请求-响应风格的接口增加默认的超时

### ISSUE THREAD

**Issue by sunng87** [leancloud/js-realtime-sdk#190]
目前 native 平台上这类的接口（比如登录、查询对话）超时设置为 20 秒，js 客户端也应该有这个超时机制，确保在服务器端没有响应时客户端的回调也会触发。

服务器端没有响应的场景包括访问超过流控的情况，这时服务器端不会响应多余的请求，对客户端来说就是超时的结果。

**Comment by sdjcw** [comment]
最近因为 Uber 抢红包的问题，云引擎也开始在服务端默认设置超时时间。是不是我们所有服务端一起梳理下，都加上超时时间，并且统一下时间，包括文档说明都一次性加上？

> 服务器端没有响应的场景包括访问超过流控的情况

这个体验优点不友好，是否能发现达到并发上限就直接响应 503 呢？

**Comment by sdjcw** [comment]
关联 https://github.com/leancloud/cloud-code/issues/574
