### ISSUE TITLE
[Android + react native] 使用api时无效的字符错误

### ISSUE THREAD

**Issue by peng051410** [leancloud/js-realtime-sdk#193]
我在react native 中使用此api，报无效的字符错误，主要只执行以下代码：
`rt = AV.realtime({
                appId: '2345',
                clientId: 'lean1234',
                encodeHTML: true
            });`

说明：在ios中没有问题， android版本为5.0.0，谢谢！

**Comment by leeyeh** [comment]
请给出具体的错误信息与错误堆栈。如果可能请给出可运行的代码来帮助我们复现问题。谢谢

**Comment by carlos-wong** [comment]
遇到同样的问题，只是执行一遍初始化，rt = AV.realtime({ appId: '2345', clientId: 'lean1234' });
React Native中会出现JSON Parse error: Unrecognize token '<'
2.3.2， 2.4.0这两个版本我都试过，我使用的RN版本为0.20.0

**Comment by carlos-wong** [comment]
@leeyeh 是否需要安装android的SDK?我安装realtime的SDK安装的时候还编译了一些.o文件，是不是这个问题？
./node_modules/bufferutil/build/Release/obj.target/bufferutil/src/bufferutil.o
./node_modules/react-native/node_modules/fbjs-scripts/node_modules/babel/node_modules/chokidar/node_modules/fsevents/build/Release/obj.target/fse/fsevents.o
./node_modules/react-native/node_modules/ws/node_modules/bufferutil/build/Release/obj.target/bufferutil/src/bufferutil.o
./node_modules/react-native/node_modules/ws/node_modules/utf-8-validate/build/Release/obj.target/validation/src/validation.o
./node_modules/utf-8-validate/build/Release/obj.target/validation/src/validation.o

**Comment by carlos-wong** [comment]
@leeyeh 我测试了一下发现engine.getServer里面ajax的xhr.onload返回的xhr.responseText是一个html的内容

ajax of realitme lib data: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<h1>400 Bad Request</h1>
<p>Your browser sent a request that this server could not understand. Sorry for the inconvenience.<br/>
Please report this message and include the following information to us.<br/>
Thank you very much!</p>
<table>
<tr>
<td>URL:</td>
<td>http://localhost</td>
</tr>
<tr>
<td>Server:</td>
<td>chat3</td>
</tr>
<tr>
<td>Date:</td>
<td>2016/04/17 17:38:24</td>
</tr>
</table>
<hr/>Powered by Tengine</body>
</html>

**Comment by carlos-wong** [comment]
我把生成的url在pc上通过浏览器打开是能返回包含ttl和server的json数据，怎么在react native里面请求就变成返回一上面那个html文件的内容

**Comment by leeyeh** [comment]
收到，我调查一下。

**Comment by carlos-wong** [comment]
我现在也正在查，麻烦有结果了发个消息

**Comment by carlos-wong** [comment]
@leeyeh 我目前自己的解决办法就是把  
ajax(url, function (error, data) {
    if (data) {
      data.expires = tool.now() + data.ttl * 1000;
      cache.server = data;
      callback(data);
    } else {
      cache.ec.emit(eNameIndex.error);
    }
  });
这个部分修改成使用axios的请求，就能获得websocket服务器
