### ISSUE TITLE
RoomObject.close 的API应该提供

### ISSUE THREAD

**Issue by sheniceice** [leancloud/js-realtime-sdk#195]
RoomObject.close函数应该提供API

**Comment by leeyeh** [comment]
我不是很明白这个问题。

**Comment by wangxiao** [comment]
这个功能应该只有在客户端才会使用，因为服务端的长连接在一段时间空闲后会自动断开。

**Comment by leeyeh** [comment]
实时通信中并没有「关闭一个会话」的概念，你可以 leave 这个会话，可以将所有人 remove，但是不能 close。

**Comment by sheniceice** [comment]
实际上我是在服务端做这么一个实时通信功能，想要的效果是服务端realtimeObj.close()能够立即关闭当前的通信，但是当我realtimeObj.close()会与websocker断开连接，但是此时RoomObject还是存在的，这个时候RoomObject.send还是会继续发送消息，此时会报错。
       所以我的目的是能够发送一条实时通信之后服务端马上断开连接

**Comment by sheniceice** [comment]
服务端的长连接在一段时间空闲后会自动断开，关键是这个长连接的过程中会打印出很多不能send的错误，这是我不想看到的，就算 leave 这个会话，这个会话依然会send消息

**Comment by wangxiao** [comment]
仍然没理解你的需求。

一个疑问是，你代码为什么不知道你已经 close 了？
你已经执行了 close，最简单的一个实现是可以标记一下这个状态（如 `isClose = true`），然后所有 send 方法就不再 send，相当于在 send 前面做好判断（如 `if (!isClose){ send(); } ` ）。

**Comment by sheniceice** [comment]
realtimeObj.on('create', function () {
        conversationObj.send(data, {
            type: 'text'
        }, function () {
            realtimeObj.close();
        });
});     //你看，我如果在回调里面关掉的话，不管你说的if (!isClose){ send(); }这个判断放哪里，其实都是不会影响到已经创建的这个conversationObj的，send依然还是会send，因为这个conversationObj在第一次发出消息后就已经存在了，不会因为这个if (!isClose)而不触发send函数

**Comment by sheniceice** [comment]
所以ws一定会抛出一次'cannot call send() while not connected'错误的，我想问的是leancloud能不能消除这次错误

**Comment by wangxiao** [comment]
我觉得 SDK 层面报这个错误应该是正常逻辑，类似于如果你有一个对象 aaa.bbb.ccc，但是你执行了 `delete aaa.bbb; `，那么你应该是在代码中知晓的，而不是指望浏览器在你执行 `console.log(aaa.bbb.ccc);` 的时候不报 `Cannot read property 'ccc' of undefined`。

**Comment by sheniceice** [comment]
是这样的，我执行delete aaa.bbb后，这个console.log(aaa.bbb.ccc)并不是我要执行的，而是我aaa.bbb.ccc没有删除，也就是leancloud没有提供删除aaa.bbb.ccc的方法导致aaa.bbb.ccc中的功能函数send在维持心跳的时候会继续执行，但是这个时候我已经delete aaa.bbb了，也就是关闭了WebSocket，此时send就会报错'cannot call send() while not connected ws'。所以我觉得leancloud提供一个RoomObject.close是有必要的。

**Comment by leeyeh** [comment]
你说的这个问题确实存在：https://github.com/leancloud/js-realtime-sdk/issues/140#issuecomment-149562037
我们在新版的 SDK 中已经修复，会在近期发布。

**Comment by sheniceice** [comment]
嗯嗯，谢谢~

**Comment by wangxiao** [comment]
感谢反馈。
因为已有重复 issue，关闭此 issue。
