### ISSUE TITLE
限制一下查询对话时几个字段的类型

### ISSUE THREAD

**Issue by sunng87** [leancloud/js-realtime-sdk#197]
发现有用户对 order 字段传的是一个数组 `["-lm??where={\"objectId\":\"...\"}","-lm"]`

限制包括：

* `limit` `skip` 是数字
* `where` 是 object
* `sort` 是字符串

**Comment by leeyeh** [comment]
这个 3.0 已经解决了

**Comment by sunng87** [comment]
好的，评估一下 3.0 的进度吧，如果 3.0 还需要一段时间的话可以考虑先在 2.x 上限制一下
