### ISSUE TITLE
[proposal] 新增 Pub / Sub 客户端

### ISSUE THREAD

**Issue by leeyeh** [leancloud/js-realtime-sdk#198]
### 目的

v3 的目标之一是整合聊天 SDK 与「推送」SDK，复用连接层。目前的 [JavaScript Push SDK](https://leancloud.cn/docs/js_push.html) 实现是建立在我们的推送协议上的，推送协议是为 Android SDK 的推送功能设计的，在 Web 与 Node.js 更加通用的需求是 Pub/Sub。一个典型的 use case 是工单系统的新回复推送（既有人回复工单后所有打开这个工单的页面都会自动更新这条回复）。要实现 Pub/Sub，目前的推送协议并不能胜任：
1. Pub/Sub 模型中的 client 不需要持久化。推送协议中的 client 对应 Installation 表中的一个设备（InstallationId），而 Pub/Sub 模型中的 client 是匿名的，在客户端销毁后就不再有人关心了。比如在工单系统中，一个 client 的生命周期在 tab 关闭后就结束了，而同一个浏览器中可以同时拥有多个 client，如果使用推送协议，会往 Installation 表中写入大量无效数据。
2. Pub/Sub 模型中的消息一般不需要持久化。
3. Pub/Sub 模型需要有权限控制，而推送协议没有机制支持。在工单系统的例子中，消息是在工单回复的 afterSave hook 中发送的，而在浏览器中订阅了工单 channel 的 client 是不允许发送消息的。
### 方案

目前想到的一个方案是基于暂态对话来实现，每个 channel 对应一个 conversation，由于对话的暂态属性，上述 1，2 条问题不存在。问题 3 可以通过在工单的 afterSave hook 中使用 Rest API 发送消息之前进行签名，在 _messageReceived hook 中验证签名的方式解决。

具体到在 SDK 中，实现 PubSubClient 类，将 Conversation 等概念封装为的 Pub/Sub 模型中的概念。提供 Realtime#createPubSubClient（与 Realtime#createIMClient 对应）。

基于暂态对话方案的潜在的问题有：
- 会污染 Conversation 表，与聊天共同使用可能会有问题，建议分成两个 app。
- Pub/Sub client 的特点是持续时间短，数量大，每个 client 都是唯一 ID 的，在现有的计费模式下容易出现高额账单。

**Comment by leeyeh** [comment]
cc @leancloud/push @jwfing any opinion?

**Comment by sunng87** [comment]
我先想想啊，咱们下周二讨论一下

这个我非常想做

**Comment by sunng87** [comment]
设计详见
leancloud/avoscloud-push#823

**Comment by musicode** [comment]
我想了解 Pub/Sub 模型 现在是什么进度了呢？

**Comment by leeyeh** [comment]
Closed in favor of mqtt.
