### ISSUE TITLE
React native中报错Requiring unknown module "child_process"

### ISSUE THREAD

**Issue by LzxHahaha** [leancloud/js-realtime-sdk#202]
```
import {realtime} from 'leancloud-realtime';
...
let realtimeObj = AV.realtime({
    appId: xxx,
    clientId: xxx
});

// 一旦有这句，reload就报错
realtimeObj.on('open', function() {
    console.log('实时通信服务建立成功！');
});
```

查了一下，是xmlhttprequest里引用的这个包，然后这个包在RN中不被支持

**Comment by leeyeh** [comment]
你好，请问你是用哪个版本的 React Native，哪个版本的 SDK，开发环境是 Android/iOS、Mac/Windows？

另外，我们正在对下个版本的 SDK 进行公开测试，欢迎使用：https://github.com/leancloud/js-realtime-sdk/releases/tag/3.0.0-beta.1

**Comment by LzxHahaha** [comment]
哦我是直接`npm install leancloud-realtime`安装的，换个版本可以用了，但是照文档上的demo来写似乎没有效果，有其他参考吗
