### ISSUE TITLE
请问 leanmessage-javascript-sdk 跟该版本有什么区别

### ISSUE THREAD

**Issue by quansenx** [leancloud/js-realtime-sdk#21]
leanmessage-javascript-sdk 是否会持续更新。

**Comment by wangxiao** [comment]
不会了。js-realtime-sdk 会作为后续实时通信的唯一 SDK 作为推荐。

**Comment by quansenx** [comment]
@wangxiao js-realtime-sdk 对浏览器支持如何。

**Comment by wangxiao** [comment]
支持高版本浏览器，准确的说是目前支持 websocket 的浏览器。

这里解释下，目前因为移动端和高级浏览器的量越来越大，尤其是移动端，
所以目前的定位是轻量高性能。

不排除后续会支持 flash socket 来兼容浏览器。
