### ISSUE TITLE
react native 报跨域错误

### ISSUE THREAD

**Issue by musicode** [leancloud/js-realtime-sdk#214]
![image](https://cloud.githubusercontent.com/assets/2732303/15068426/cd99c614-13a9-11e6-8973-f808e5a66f4d.png)

* "avoscloud-sdk": "^1.0.0-rc7",
* "leancloud-installation": "^1.0.0",
* "leancloud-realtime": "^3.0.0-beta.1",
* "leancloud-realtime-typed-messages": "^1.0.0-beta.1",

在 react native 25 中会报如上错误，本地开发，初始化代码如下：

```javascript
realtime = new Realtime({
    appId,
    region: 'cn',
    noBinary: true,
    //pushOfflineMessages: true,
})
```

**Comment by leeyeh** [comment]
为了方便复现问题，能否帮忙做以下两件事情中的任意一件：
1. 测试 https://github.com/leeyeh/leancloud-realtime-react-native-demo 能否正常工作。
2. 类似上面这个 repo，将你完整的可运行代码共享给我。

**Comment by musicode** [comment]
@leeyeh 
测试  leancloud-realtime-react-native-demo ，报了相同的错

我的 react-native 版本是 0.25.1，多谢~

**Comment by musicode** [comment]
![image](https://cloud.githubusercontent.com/assets/2732303/15069015/93b8791e-13ad-11e6-9419-bf6dd27056d2.png)
补图

**Comment by leeyeh** [comment]
那样的话我会先怀疑是网络问题，请试一下这个命令返回的是什么：
```
curl https://router-g0-push.leancloud.cn/v1/route\?appId\=anruhhk6visejjip57psvv5uuv8sggrzdfl9pg2bghgsiy35\&secure\=true
```

**Comment by musicode** [comment]
@leeyeh 

curl https://router-g0-push.leancloud.cn/v1/route\?appId\=anruhhk6visejjip57psvv5uuv8sggrzdfl9pg2bghgsiy35\&secure\=true

{"groupId":"g0","server":"wss:\/\/rtm56.leancloud.cn:6799\/","ttl":3600,"secondary":"wss:\/\/rtm51.leancloud.cn:6799\/"}%

**Comment by leeyeh** [comment]
ok 我复现了，开了 remote debugger 之后就会出现，我需要调查一下。

**Comment by musicode** [comment]
好的，期待修复版本！

**Comment by musicode** [comment]
@leeyeh 能了解一下大概什么时候有修复版本可用么？

**Comment by leeyeh** [comment]
我准备替换掉 superagent，但是得下周才有时间，如果影响开发的话可以先停止使用 chrome debugger。
musicode <notifications@github.com>于2016年5月6日 周五19:13写道：

**Comment by musicode** [comment]
好的，我先用回 2.x 版本

**Comment by leeyeh** [comment]
需要提醒一下，2.x 与 3.x 的差异比较大。

**Comment by musicode** [comment]
今天我本来想升级3的，可是用不了，所以只能退回去啦~

**Comment by leeyeh** [comment]
我做了一些调查，因为我需要内置的 Promise 支持，superagent 是目前最合适的 Rest API client。

对于在 Chrome 调试时报的跨域问题，在 import ’react-native‘ 之后加入 `delete global.XMLHttpRequest` 即可绕过。https://github.com/leeyeh/leancloud-realtime-react-native-demo/commit/03f27f0aaff13f87b853e0da56e49f901ce6a6e9

**Comment by musicode** [comment]
多谢~

**Comment by musicode** [comment]
我加了 `delete global.XMLHttpRequest` 之后，之前发给后端的请求都挂了，报如下错误：

XMLHttpRequest cannot load [url]. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8081' is therefore not allowed access.
fetch.js:12 response TypeError: Network request failed
    at XMLHttpRequest.xhr.onerror (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:15462:8)

**Comment by leeyeh** [comment]
确实可能有这样的副作用，我再研究下。
