### ISSUE TITLE
[建议] 3.0 可以避免对 avoscloud-sdk 的依赖吗

### ISSUE THREAD

**Issue by ydfzgyj** [leancloud/js-realtime-sdk#219]
在前端代码里 APP KEY 毕竟不是很安全……
富媒体对 avoscloud-sdk 的依赖好像就是 AV.File 和 AV.GeoPoint，但像我这样上传文件用已有的后端接口的用户不需要调用 save 之类的方法
希望可以对我们这部分用户只对 _lcfile 和 _lcloc 做一个简单的封装，只满足收发富媒体消息的需求，而需要前端上传文件的用户可以再单独引入 avoscloud-sdk 做上传
这样就不需要在前端使用 APP KEY 了

**Comment by leeyeh** [comment]
Realtime SDK 本身没有依赖 `avoscloud-sdk`，富媒体消息是通过 `leancloud-realtime-typed-messages` 这个额外的 package 支持的，这个 package 依赖 `avoscloud-sdk`。https://leancloud.cn/docs/realtime_guide-js.html#leancloud_realtime_typed_messages

如果你不希望我们提供的富媒体消息类，可以自己创建：https://leancloud.cn/docs/realtime_guide-js.html#创建新的消息类型

**Comment by sunng87** [comment]
好设计！

**Comment by leeyeh** [comment]
@ydfzgyj 事实上，你描述的需求，是可以使用我们提供的基于 `avoscloud-sdk` 的富媒体消息类。如果只是收消息的话，不去初始化 `avoscloud-sdk` 可是可以的。

**Comment by ydfzgyj** [comment]
@leeyeh 可能是我描述的不够清楚，我的问题并不在于自定义消息类型
我已经引用了leancloud-realtime-typed-messages，但是我是希望这个 package 不要依赖 avoscloud-sdk 也能使用，因为觉得在前端代码里放 APP KEY 不安全。我试了一下不初始化 avoscloud-sdk，控制台里会报错……
实际上我也可以绕过这个 package，收的话自己封装 message.content，发的话因为我们已经有基于 LeanEngine 的后端，可以调 RESTful API 去发送消息（还没有仔细去看可不可以直接构造一个 Message 类去 send ……）
但是如果在 SDK 里能直接提供不依赖 avoscloud-sdk 的用法，肯定更优雅吧哈哈，我猜想像我们这种有后端又有实时通信需求的还是挺多的吧……

**Comment by leeyeh** [comment]
如果你说的是 `Get current user failed. It seems this runtime use an async storage system, please new AV.File in the callback of AV.User.currentAsync().` 这是个 warning，不去管他不会有问题。

可以试下这 demo: [收](http://jsplay.avosapps.com/xep/edit?html,js,console) [发](http://jsplay.avosapps.com/vug/embed?html,js,console,output)

关于 leancloud-realtime-typed-messages。如果想用我们提供的 AV.File 这个类那么 avoscloud-sdk 是省不掉的。如果不用，那么自定义一个 YourFileMessage 消息类型就可以了。事实上，我们提供的 FileMessage 是通过同样的机制扩展出来的：https://github.com/leancloud/js-realtime-sdk/blob/next/typed-messages/src/file-message.js。

**Comment by ydfzgyj** [comment]
已测，收消息的话确实那个报错不管也没有问题，但发的话不行，因为要求发送的那个文件必须在服务端保存……包括收取历史消息的时候会有些图片的 _lcfile 没有 id ，也会被直接 throw 出来……
不是很明白一定要保存在本地的意义，用 withURL 也可以的吧？

**Comment by leeyeh** [comment]
> 用 withURL 也可以的吧？

可以。http://jsplay.avosapps.com/poj/embed?js,console

其实我还是推荐使用自定义消息类型，因为我理解你需要发送信息的并不是一个完整的 AV.File，而只是一个 url（在用已有的后端接口上传文件之后）。那样其实没有必要用我们提供的富媒体消息类型。

```javascript
class FileMessage extend AV.TypedMessage {
  constructor(url) {
    super();
    this.url = url;
 }
}
AV.messageType(1);
AV.messageField('url');
```

不知道我对需求理解的对不对。

**Comment by ydfzgyj** [comment]
但是我的消息类型需要和旧有的聊天记录以及其他端兼容……
自定义的类型是正数，和默认的负数就不一致了呀
基于这个原因我必须得用你们提供的富媒体消息吧
我自己改typed-messages.js倒是也行……但是以后升级版本又是麻烦事

**Comment by leeyeh** [comment]
> 但是我的消息类型需要和旧有的聊天记录以及其他端兼容……

明白了。SDK 在发送前会检查 file.id 是为了确保这个文件已经上传，你可以在通过自己的接口上传之后返回相关的信息自己构造一个。可以参考 SDK 是怎么构造一个已经存在的 AV.File 的：https://github.com/leancloud/js-realtime-sdk/blob/next/typed-messages/src/file-message.js#L42-L53

**Comment by leeyeh** [comment]
实在不行还有大杀器：直接构造一个 `AV.Message`，自己拼 `_lctype`、`_lcfile` 等字段，想发什么发什么。当然从可维护性角度我并不推荐这么做。

**Comment by ydfzgyj** [comment]
OK，尝试用 File.withURL 构造再强行赋值 file.id 可以发送成功
但收消息时很多从 2.x 传过来的文件都没有 id，好像我们用户是做不到在 parse 之前就注入一个 id 来保证解析的？希望兼容一下

**Comment by leeyeh** [comment]
> 尝试用 File.withURL 构造再强行赋值 file.id 可以发送成功

👍

> 做不到在 parse 之前就注入一个 id 来保证解析的

```javascript
class YourFileMessage extends AV.FileMessage {
  static parse(json, message) {
    json.id = json.id | 'just fake one';
  }
}
```

设计上是支持这样的，我还没这样试过 😁。

**Comment by ydfzgyj** [comment]
ImageMessage 这些并不能再去调这个子类……

**Comment by leeyeh** [comment]
Right. 我会兼容一下没有 ID 的情况，并且考虑给 Realtime 增加一个 beforeParse 的 hook。

**Comment by ydfzgyj** [comment]
好的，感谢！
