### ISSUE TITLE
安卓4.4.4 微信webView不支持？？

### ISSUE THREAD

**Issue by zhlhuang** [leancloud/js-realtime-sdk#222]
安卓4.4.4 微信webView不支持？？
![image](https://cloud.githubusercontent.com/assets/6230834/15240411/05fb335e-191c-11e6-9add-222b96285ee8.png)

**Comment by leeyeh** [comment]
请问是不是使用了 leancloud-realtime-typed-messages?

**Comment by leeyeh** [comment]
你好，我们发布了 leancloud-realtime v3.0.0-beta.3 以及 leancloud-realtime-typed-messages v1.0.0-beta.2，请再试下。谢谢
