### ISSUE TITLE
您好，请问如何去掉时间的监听，单页的页面打开多次，事件on("message")等被注册了多次了

### ISSUE THREAD

**Issue by xgzl87** [leancloud/js-realtime-sdk#236]

**Comment by leeyeh** [comment]
可以使用 [`removeListener`](https://nodejs.org/api/events.html#events_emitter_removelistener_eventname_listener) or [`removeAllListeners `](https://nodejs.org/api/events.html#events_emitter_removealllisteners_eventname)。
我们所有会派发事件的类都实现了 EventEmitter 接口，请参考：https://nodejs.org/api/events.html
