### ISSUE TITLE
为何在3.0.0 Beta4版本的AMD加载方法中使用named module呢？

### ISSUE THREAD

**Issue by dangyuluo** [leancloud/js-realtime-sdk#249]
realtime.browser.js 中第3行
`define('leancloud-realtime', ['exports'], factory)`
好像RequireJS不推荐这种做法，降低了移植性

**Comment by leeyeh** [comment]
使用 named module 是因为在 https://github.com/leancloud/js-realtime-sdk/blob/v3.0.0-beta.4/typed-messages/dist/typed-messages.js#L3 中 `typed-messages` 这个插件依赖 `leancloud-realtime`，如果用匿名模块的话，`typed-messages` 就会找不到 `leancloud-realtime`。

这个模块名字是定死的，不再能作为匿名模块使用，如果有遇到因此造成的任何问题请描述下具体问题。欢迎提出更好的方案。
