### ISSUE TITLE
React Native(Android)中import { Realtime } from 'leancloud-realtime'时提示Attempted to assign to readonly property

### ISSUE THREAD

**Issue by zoomyu** [leancloud/js-realtime-sdk#281]
在React Native(Android)使用 npm 安装 SDK：
   npm install leancloud-realtime@next --save
后import { Realtime } from 'leancloud-realtime'时提示Attempted to assign to readonly property
![screenshot_2016-06-26-11-40-05](https://cloud.githubusercontent.com/assets/10228162/16360409/f95a3056-3b93-11e6-978c-127af4a59720.png)
package.json
"dependencies": {
   "leancloud-realtime": "^3.0.0-beta.4",
    "react": "^15.0.2",
    "react-native": "^0.26.1",
    ...
    "react-redux": "^4.4.5",
    "redux": "^3.5.2",
    "redux-thunk": "^2.0.1"
},
这是什么情况？

**Comment by leeyeh** [comment]
能否试一下这个分支：`npm i leeyeh/js-realtime-sdk#dist`

**Comment by leeyeh** [comment]
所以是解决了这个问题吗？如果是的话，我好合并到主干然后尽快发一个 patch release。

**Comment by zoomyu** [comment]
解决了，现在运行正常了
