### ISSUE TITLE
为什么V3不能用import导入

### ISSUE THREAD

**Issue by bluewind86** [leancloud/js-realtime-sdk#287]
import { Realtime } from 'leancloud-realtime'; 
这种方式会报错。貌似v2就可以

------------------------------------------------------
试了一下，import { Realtime } from '../../../node_modules/leancloud-realtime/dist/realtime.browser';
这种方式倒是可以导入

**Comment by leeyeh** [comment]
是支持的。

请问是在什么环境中使用，报了什么错？

**Comment by bluewind86** [comment]
是在浏览器环境下。我的问题和这位同学的问题是一样的。
https://forum.leancloud.cn/t/leancloud-js-v3-import-realtime-from-leancloud-realtime/8899
这个帖子里有报错截图

**Comment by leeyeh** [comment]
那个贴子的截图显示 leancloud-realtime 模块找不到。

如果 import { Realtime } from '../../../node_modules/leancloud-realtime/dist/realtime.browser' 可以的话，说明是你用的打包程序在解析模块时出了问题。

如果可能能麻烦提供以下你的构建过程吗，我好在本地复现一下。最好是一个 repo，最简单的情况能复现问题就行。

**Comment by iwinux** [comment]
我来补充一个可以复现的 demo: https://github.com/iwinux/leancloud-realtime-sdk-287

**Comment by leeyeh** [comment]
fixed in v3.1.1
