### ISSUE TITLE
如何防止两个用户私聊的场景出现重复会话

### ISSUE THREAD

**Issue by musicode** [leancloud/js-realtime-sdk#293]
操作步骤如下：

1. 两个用户（a 和 b）私聊，建立 unique 会话
2. a 用户 quit 会话，此时 a 用户的会话列表拉不到该会话，但是 b 用户还能拉到该会话
3. a 用户重新建立和 b 用户的 unique 会话，此时，a 用户有一个和 b 用户的会话，b 用户出现重复会话

如何解决呢？

**Comment by leeyeh** [comment]
这个现象是符合预期的。

如果简单的希望 b 用户在 a quit 之后不再在该会话中，可以在 a quit 之前 kick 掉 b。这个的缺点是下次再创建 unique 会话是创建的会是一个新的会话。

不知道这个方案能否满足需求。

**Comment by musicode** [comment]
如果想实现微信那样的会话列表，即 a quit 之后，b 的会话列表其实是不受影响的，是不是没法做到了？

**Comment by leeyeh** [comment]
「建立 unique 会话」的逻辑是这样的，查找是否存在成员为 [A, B] 的会话，如果存在则返回这个会话，如果不存在则创建一个成员为 [A, B] 的会话并返回，如果 A quit 了之后，这个会话成员就变成只有 B 一个人的会话了。

之后 A 再创建 unique 会话时，则之前的这个会话就不再满足要求了，于是就会再新建一个。

有一种稍复杂的方案可以实现，「创建一个 A, B 之间的唯一会话，A quit 之后再找还能找到原来的那个会话」：使用 md5([A, B]) 来标识这个会话，将这个标识保存在 Conversation 的一个字段中（比如可以用 name），为这个字段添加唯一索引，然后再需要加入这个唯一会话时先查找一个是否存在这个 name 的会话。

**Comment by musicode** [comment]
> 为这个字段添加唯一索引

没懂.

我理解是给 attributes 加一个标识字段，然后用以下代码查询是否存在：

```javascript
var query = a.getQuery();
query.equalTo('attr:xxx', 'xxx');
query.find().then(function (conversations) {
    if (Array.isArray(conversations) && conversations.length === 1) {
         // 使用 conversations[0]
    }
    else {
        // 新建会话
    }
});
```

不知道理解的对不

**Comment by leeyeh** [comment]
也是可以的，除了：
`query.equalTo('attr.xxx', 'xxx');`

为这个字段添加唯一索引是为了从数据库的层面保证不会重复创建同一个这个字段的会话。

**Comment by musicode** [comment]
sdk 有 api 可以添加唯一索引么？

**Comment by leeyeh** [comment]
索引是通过控制台添加的，并且不能添加二级字段 attr.xxx 的索引，所以刚才的例子中我使用了 name 作为存放标记的字段。

**Comment by musicode** [comment]
没有 api，在实际场景是不可用的，谁有闲心手动加索引...

**Comment by leeyeh** [comment]
这个操作是针对字段的，是一次性的。

**Comment by musicode** [comment]
是每个会话都要操作一次么？还是说有个配置项可以统一设置到所有现有的会话，和未来要创建的会话？

**Comment by leeyeh** [comment]
索引不是针对某个数据的，而是针对一个 class 的某个字段，操作方法可以参考：https://leancloud.cn/docs/faq.html#当数据量越来越来大时_怎么加快查询速度_

**Comment by musicode** [comment]
懂了，多谢！

**Comment by musicode** [comment]
顺便问一句，如果要实现本地删消息，即自己的删除操作不影响对方的消息记录，是不是要在本地缓存一个列表，一旦从服务器拉过，就不再拉取，每次都从本地读，因此删除也和服务器无关了

**Comment by leeyeh** [comment]
是的。

**Comment by musicode** [comment]
![image](https://cloud.githubusercontent.com/assets/2732303/16679751/9152f9ec-451c-11e6-8caa-fea7bc3b1dc1.png)

```javascript
var query = a.getQuery();
query.equalTo('attr:id', '668578_873768');
query.find().then(function (conversations) {
    conversations 是个空数组.....
});
```

是不是 sdk 有 bug？

**Comment by leeyeh** [comment]
query.equalTo('attr.id', '668578_873768');

**Comment by musicode** [comment]
多谢~
