### ISSUE TITLE
conversation 有人修改 attributes，其他成员貌似不能立即获得最新 attributes

### ISSUE THREAD

**Issue by musicode** [leancloud/js-realtime-sdk#299]
假设要在 attributes 存储很多数据，比如群成员信息，如果有人修改了 attributes，如下：

```javascript
conversation.setAttributes(changes, true);
conversation.save()
```

会话里的其他成员多久才能同步到这些数据呢？

**Comment by leeyeh** [comment]
不会同步。

有个简单的方法解决，自定义一个 AttributesUpdated 的暂态消息，修改成功之后往群里发一个这个消息，当前在线的成员收到消息之后就去 fetch 一下最新的数据。

**Comment by musicode** [comment]
有接口可以全量更新 attributes 么？还是说这个暂态消息需要带上更新的字段，这样就不用请求了，直接本地更新即可？

**Comment by leeyeh** [comment]
全量更新 attributes 指的是什么？fetch 的话会更新对话所有的属性。

**Comment by musicode** [comment]
懂了，conversation.fetch() 就是我想要的
