### ISSUE TITLE
RealtimeObject.close()之后好像heartbeat依然在运行

### ISSUE THREAD

**Issue by cnjsstong2** [leancloud/js-realtime-sdk#30]
close之后过一段时间会重复出现以下错误：

    WebSocket is already in CLOSING or CLOSED state.      
    wsSend                               AV.realtime.js:348
    (anonymous function)                 AV.realtime.js:368 

感觉像是因为heartbeat还持续在运行。

另外目前有哪个函数可以获取RealtimeObject当前的状态吗（open，closed等）？

**Comment by wangxiao** [comment]
感谢反馈，close 之后确实有点问题，我修复一下。
目前没有获取运行状态的接口，我考虑暴露一个。

目前支持几个特定的事件，可以监控这个状态变化，

open 服务开启
close 服务关闭
resue 正在断开重连

**Comment by wangxiao** [comment]
bugfix
https://github.com/leancloud/js-realtime-sdk/pull/33

**Comment by wangxiao** [comment]
已经修正发布 2.0.1 版本  https://github.com/leancloud/js-realtime-sdk/releases/tag/2.0.1
