### ISSUE TITLE
考虑是否需要暴露一个获取服务状态的接口

### ISSUE THREAD

**Issue by wangxiao** [leancloud/js-realtime-sdk#31]

**Comment by wangxiao** [comment]
@cnjsstong2 你之前遇到怎样的情况，需要获取这个状态？

**Comment by cnjsstong2** [comment]
当尝试close一个rtObject时，如果状态不为open就会出错（比如还没有open成功）。如果对close增加一些处理应该也可以。

**Comment by wangxiao** [comment]
好的，确实有这个问题，调用上可能会不够方便。
目前可以通过监听 open 这个事件来解决。

**Comment by wangxiao** [comment]
我暂时不暴露服务状态的接口了，感觉意义不大，因为有对应的事件来做动作。

然后关于 close 这个方法，在这种情况下，仅提供友好的报错提示。

https://github.com/wangxiao/js-realtime-sdk/commit/bffbc08a07f32ef6721bcd4c5da591e4827e3484
