### ISSUE TITLE
android 4.4以下不支持websocket情况下能不能使用长轮询呢？

### ISSUE THREAD

**Issue by xgzl87** [leancloud/js-realtime-sdk#315]

**Comment by wangxiao** [comment]
long pulling 完全是另外一套技术架构，目前 LeanCloud 服务端不支持，而且也不打算支持。long pulling 同时也不是双向双工通信，是一种开销很大，性能很差的技术。

而且不确定会不会有别的问题。

**Comment by xgzl87** [comment]
嗯，那低版本的就比较蛋疼了。开销确实不小，需要cpu不断的去请求，但是低版本客户端没啥好的办法吧

**Comment by wangxiao** [comment]
低版本其实是支持的，通过 JS 实时通讯 2.0 版本，加载 Flash 可以兼容部分机型的 webview，不过这个也是分机型的，得具体看，如果都不行，那就只能降级为通过 REST API 定时轮询了。
