### ISSUE TITLE
新对话属性修改 API

### ISSUE THREAD

**Issue by leeyeh** [leancloud/js-realtime-sdk#330]
目前 `Conversation#setAttribute[s]` 的实现是错误的。准备实现 https://github.com/leancloud/paas/issues/846 ，分三步

~~\- [ ] 实现私有的 `Conversation#set`，将 `Conversation#setAttribute[s]` 与 `Conversation#setName` 代理到 `Conversation#set`，发布 v3.1 的一个 patch。~~
- [x] 公开 `Conversation#set`，deprecate `Conversation#setAttribute[s]` 与 `Conversation#setName`，增加 `Conversation.defineProperties` in v3.2。
- [x] 移除 `Conversation#setAttribute[s]` 与 `Conversation#setName` in v4。

**Comment by musicode** [comment]
以前用 conversation.setAttribute[s]() 的都改为 conversation.set() 呗？

**Comment by musicode** [comment]
好久没更新版本了啊
