### ISSUE TITLE
评估兼容方案

### ISSUE THREAD

**Issue by wangxiao** [leancloud/js-realtime-sdk#34]
引入 flash 来兼容 websocket 。

**Comment by liuyanghejerry** [comment]
希望可以以插件的形式引入，这样移动端或者现代浏览器中可以不必加载这部分内容

**Comment by hellolibo** [comment]
我们正使用 https://github.com/gimite/web-socket-js 做兼容，但是需要在服务端安置跨域文件。这个现在怎么处理？

**Comment by wangxiao** [comment]
我尽快搞下 flash 支持，大家可以先用当前版本写业务逻辑。感谢大家提的建议。

**Comment by xufanbb** [comment]
请尽快给出方案啊，谢谢。在等着呢！

**Comment by wangxiao** [comment]
请 @sunng87 帮忙 review 下，demo 测试通过。
https://github.com/leancloud/js-realtime-sdk/pull/66
其他事情在 pull request 中讨论，关闭该 issue。

**Comment by hellolibo** [comment]
因为跨域名的问题，我使用了 WebSocketMainInsecure.swf
但是还是出现下面的问题。
```
[WebSocket] debug enabled
[WebSocket] policy file: xmlsocket://chat8.avoscloud.com:843
[WebSocket] cannot connect to Web Socket server at wss://chat8.avoscloud.com:5799/ (SecurityError: Error #2048)
make sure the server is running and Flash socket policy file is correctly placed
[WebSocket] Error: Error #1009
[WebSocket] closed
WebSocket closed.
通信中断

```

**Comment by wangxiao** [comment]
对的，你不是用的我们提供的方法，请参考 Demo2 的代码，文档我们会尽快发布。

**Comment by wangxiao** [comment]
新文档已经发布，目前使用可以抓 Master 最新的代码使用，demo2 已经兼容 IE8。
相关文档地址，查阅「兼容」相关内容   https://leancloud.cn/docs/js_realtime.html
