### ISSUE TITLE
如何识别用户好友的在线情况？

### ISSUE THREAD

**Issue by hellolibo** [leancloud/js-realtime-sdk#35]
原来的watch方法也没有了.

**Comment by wangxiao** [comment]
对，现在你可以通过自己的方式去判断是否在线，我们在第二版中将这个功能去掉了。

**Comment by hellolibo** [comment]
那我如果使用老的sdk，应该也没有问题是吗？

**Comment by wangxiao** [comment]
恩，1.0 版本我们会持续维护。

**Comment by wangxiao** [comment]
2.0 我们会在近期支持一种更加简单的判断好友是否在线的方式，可以关注。

**Comment by hellolibo** [comment]
有大概的时间点吗？我这里的项目已经开始了。

**Comment by wangxiao** [comment]
大概的化，可能要等到下周才行。
https://github.com/leancloud/js-realtime-sdk/issues/36

**Comment by wangxiao** [comment]
已经修正发布 2.0.1 版本  https://github.com/leancloud/js-realtime-sdk/releases/tag/2.0.1
