### ISSUE TITLE
请问 withLastMessages 2.4.0支持吗

### ISSUE THREAD

**Issue by xgzl87** [leancloud/js-realtime-sdk#354]

**Comment by leeyeh** [comment]
支持 https://github.com/leancloud/js-realtime-sdk/releases/tag/2.4.0

**Comment by xgzl87** [comment]
为什么我用2.4.0取不到呢

**Comment by xgzl87** [comment]
老的聊天记录取不到，能取到最近发的，这是为啥

**Comment by sunng87** [comment]
这里 last message 和对话数据是分开存储的，并且有一定的过期时间，会有不存在的情况，请留意在应用层处理一下

**Comment by xgzl87** [comment]
哦，不过处理起来比较麻烦啊，只能通过RoomObject.log来处理，RealtimeObject.query是个列表没办法处理了
