### ISSUE TITLE
RealtimeObject.room(id, cb)并没有执行cb

### ISSUE THREAD

**Issue by liuyanghejerry** [leancloud/js-realtime-sdk#37]
https://github.com/leancloud/js-realtime-sdk/blob/master/src/AV.realtime.js#L966

即使id是一个已经存在的roomId，该callback并不会执行，与文档https://leancloud.cn/docs/js_realtime.html#RealtimeObject_room-1  相悖。

**Comment by liuyanghejerry** [comment]
另外，`RealtimeObject.room(id, cb)`也没有向服务端发起sign请求，而websocket的帧当中也没有join相关的操作。

**Comment by wangxiao** [comment]
非常感谢，对你使用产生的问题非常抱歉，已经提交代码，会尽快发布。
https://github.com/leancloud/js-realtime-sdk/pull/38

**Comment by wangxiao** [comment]
已经修正发布 2.0.1 版本  https://github.com/leancloud/js-realtime-sdk/releases/tag/2.0.1

**Comment by liuyanghejerry** [comment]
建议realtimeObject.room()方法中的cb回调，能将room对象直接作为参数，因为这个回调执行的比room方法返回还早：
someVar.room = null;
someVar.room = realtimeObj.room(roomId, function() {console.log(someVar.room)})
// oops, console.log prints null.
// Because callback is called before the room is returned.

而如果使用room作为回调参数的话：
 realtimeObj.room(roomId, function(room) {console.log(room)})
// this seems fine.

Node.js当中，对于这样的情况使用nextTick来调用回调，但是浏览器里就只有个setTimeout，比较丑陋，如果忍受不了这样丑陋，起码应该给这个回调一个room作为参数。

**Comment by wangxiao** [comment]
好的，这种情况我考虑一下。单独另外弄个 issue 吧，感谢反馈。
