### ISSUE TITLE
React Native 中重新进入应用 sdk 不会自动重连

### ISSUE THREAD

**Issue by leeyeh** [leancloud/js-realtime-sdk#421]
在react-native android上，真机型号是m811，登陆以后，手机一段时间没操作后重新进入应用，（这时候多数境况是sdk不会自动重连，addEventListenerlRealtime里面没有反应）如果这时候发送消息就会报错。错误出现在realtimer.browser.js的16131行；
源头应该是没有自动重连上，所以想问有什么办法能让手机在一段时间没操作后能自动重连上？

这里是我的代码

``` javascript
const Realtime = require('leancloud-realtime').Realtime;
let realtime = new Realtime({
  appId: 'xxxxxxxxxxxxxxxxx',
  pushOfflineMessages: true,
  region: 'cn', 
  noBinary: true,
});

//登陆调用
createIMClient(){
  realtime.createIMClient(this.props.userName).then(function(user) {
     ToastAndroid.show('通讯连接成功',ToastAndroid.SHORT)
       user.on('message', function(message, conversation) {
               //接收消息处理
       });
  })
}

//登陆调用
    addEventListenerlRealtime(){
        const self=this;
        realtime.on('disconnect', function() {
            ToastAndroid.show('通讯断开',ToastAndroid.SHORT)
        });
        realtime.on('reconnect', function() {
            // self.setState({isConnected:true})
            ToastAndroid.show('恢复通讯',ToastAndroid.SHORT)
        });
    }

发送消息调用
sendMessage(text){
      realtime.createIMClient(this.props.userName).then(function(user) {
          user.on('message', function(message, conversation) {
              //发送消息
          });
      })
}    


这里是sdk的代码
realtimer.browser.js的16131行抛出错误，16170行
      Connection.prototype.send = function send(command) {
        var _this2 = this;
        var waitingForRespond = arguments.length <= 1 || arguments[1] === undefined ? true : arguments[1];
        var serialId = void 0;
        if (waitingForRespond) {
          serialId = ++this._serialId;
          command.i = serialId; // eslint-disable-line no-param-reassign
        }
        debug$1('↑', trim$1(command), 'sent');
        var message = void 0;
        if (this._protocalFormat === 'protobase64') {
          message = command.toBase64();
        } else if (command.toBuffer) {
          message = command.toBuffer();
        } else if (command.toArrayBuffer) {
          message = command.toArrayBuffer();
        }
        if (!message) {
          throw new TypeError(command + ' is not a GenericCommand');
        }
        _WebSocketPlus.prototype.send.call(this, message);
        if (!waitingForRespond) {
          return _Promise.resolve();
        }
        return new _Promise(function (resolve, reject) {
          _this2._commands[serialId] = {
            resolve: resolve,
            reject: reject
          };
          setTimeout(function () {
            if (_this2._commands[serialId]) {
              debug$1('✗', trim$1(command), 'timeout');
              reject(new Error('Command Timeout.'));/////<----------------------这里抛出了错误
              delete _this2._commands[serialId];
            }
          }, COMMAND_TIMEOUT);
        });
      };
```

**Comment by leeyeh** [comment]
我有个问题，应用从后台切回前台时，链接应该已经断开了，SDK 有检测到这点么？

```
realtime.on('disconnect', function() {
    console.log('disconnect') // 看下有没有这个日志
    ToastAndroid.show('通讯断开',ToastAndroid.SHORT)
});
```

**Comment by wooter-s** [comment]
没有，检测不到；
我用了两台测试，有一台mx2的大多时候能检测到；但是m811这台机器都检测不到

**Comment by leeyeh** [comment]
这个没有检测到断开的原因我还需要调查一下，我看了下 m811 的系统还是 4.3 的，可能有关系，

有一个办法是，对于这种情况，可以通过监听 AppState，在 app 切回前台之后手动触发重连： `client._connection.disconnect()`。

顺便问一下，这个问题有在 iOS 上测试过吗。

**Comment by wooter-s** [comment]
ios我没做，所以不清楚。
有什么条件可以判断是否需要disconnect()，查看connection.current一直都是connected。
另外client对应sdk里面是哪个api得到的，没找到自己加了个
  Realtime.prototype.disconnect=function selfReconnect(){
    var connection = internal(this).connection;
    connection.disconnect()
  }

**Comment by leeyeh** [comment]
如果有可靠的方法来判断是否已经断开了的话，SDK 就自动 disconnect 了，但是现在没有。目前的逻辑是每一分钟 ping-pong 一次，如果三分钟内没有收到任何回复则认为断开调用 disconnect。
https://github.com/leancloud/js-realtime-sdk/blob/master/src/websocket-plus.js#L169-L172

从现在的现象看，应用切到后台之后链接断开，再切回前台这个定时器由于某些原因没有执行，才导致了 SDK 不知道已经断开。

一个可能的问题是，应用切回到前台时，还没有到 3 分钟。这个可以试一下等到三分钟的时候 SDK 会不会开始重连。

一种暴力的方式就是只要应用从后台被切回到前台，就主动去 disconnect（上面说的 client 其实就是你代码里的 user 实例）。

另一方面我考虑的是 SDK 再增加一个「离线」状态，区别于现在的「掉线」状态，用户可以通过 API 主动告诉 SDK 离线与上线。这样在这个 case 里，app 就可以在应用切到后台之后主动调用离线 API，然后再切回后台的时候重新上线。

**Comment by musicode** [comment]
react native ios

leancloud 最新版本

我这边打日志发现，当 app 按下 home 再锁屏之后，解锁再进入 app，会触发 disconnect -> schedule -> retry -> reconnect，此时发消息发不出去，貌似也接收不到消息

**Comment by musicode** [comment]
@leeyeh 是最新版引入的问题吗

**Comment by leeyeh** [comment]
没有。

>会触发 disconnect -> schedule -> retry -> reconnect，此时发消息发不出去，貌似也接收不到消息

这是预期中的断线重连的行为。你可以手动在 app 进入后台的时候调用 realtime.pause，在 app 返回前台的时候调用 realtime.resume 来获得更快的重连体验。

**Comment by musicode** [comment]
我是在 reconnect 之后发消息，发不出去，正常吗

**Comment by leeyeh** [comment]
不正常，发不出去异常是什么？

**Comment by musicode** [comment]
正常发消息，会收到一个 message 对象，但是 reconnect 之后，收不到这个对象了

**Comment by musicode** [comment]
发消息用的是 `conversation.send(message)`，是不是重连后的 `conversation` 对象，已经断掉了？

**Comment by musicode** [comment]
我刚测试了 `realtime.resume()`，调完之后可以正常发消息

**Comment by musicode** [comment]
@leeyeh 方便告知是什么原因吗？如果不好修，可以告知有啥临时解决办法吗，这个问题现在影响挺严重的，几乎必现。。

**Comment by musicode** [comment]
> 手动在 app 进入后台的时候调用 realtime.pause，在 app 返回前台的时候调用 realtime.resume 来获得更快的重连体验。

这样是否无法获取新消息通知了？

**Comment by musicode** [comment]
![image](https://user-images.githubusercontent.com/2732303/34336853-9fe664ac-e995-11e7-9e7f-b22cc5a656f6.png)

**Comment by musicode** [comment]
@leeyeh 这些日志对你定位问题有帮助吗

**Comment by leeyeh** [comment]
从你贴的日志看，reconnect 之后，连接都已经恢复了。抛出的异常是因为当前的 client 不再指定的对话重，因此查询历史消息发送对话都失败了。请检查有无将该用户移除对话，或者该对话是否是聊天室。

**Comment by musicode** [comment]
1. reload 后可以正常在该会话中发消息，所以该 client 肯定在会话中，不会因为重连就不在了，至少我的业务代码没做这种事
2. 我用 `client.createConversation` 创建的会话，应该是不是聊天室

**Comment by musicode** [comment]
@leeyeh 我从 v4.0.0-beta.0 试到了 v4.0.0-alpha.1，全都不行，几个月前，我用 3.x 的时候，我还专门测过这个，是可以的

**Comment by leeyeh** [comment]
您能给我一个有问题的 appid, client id 与 conversation id 吗？

**Comment by musicode** [comment]
appId Oteh7o19mRMlE7SLefeNqdBz-gzGzoHsz

clientId 279576

conversationId 5a3e38957f6fd300610cfa29

**Comment by musicode** [comment]
@leeyeh 你那边能复现问题吗

**Comment by musicode** [comment]
@leeyeh 这两天方便告知如何解决这个问题吗？我们的计划是28号发版，现在就剩这一个 bug 了...

**Comment by leeyeh** [comment]
我没有从这个 client（279576）的日志里发现任何相关的异常现象。我比较确定你上面截图中，断线重连是成功的，并且显示的 error 是服务端返回了 client 不在对话中的异常。

能麻烦你移步论坛 https://forum.leancloud.cn 来提供下更多信息吗？这个问题应该与这个 issue 没有关系了。

我希望能够看到在一次成功的复现之后，客户端的日志（最好能提供时间戳），以及相关的 id，我们好对应起来看出了什么问题。

另外一点是，你提到用 3.x 的时候是没有问题的，那你现在回滚到 3.x 这个问题还存在吗？

**Comment by musicode** [comment]
@leeyeh 你希望我在哪些关键点打日志呢？我现在用模拟器，不是每次 home + lock 都能复现，但是手机上是必现，模拟器偶尔出现问题时，打印的日志如截图所示，可以肯定的是 realtime 是重连成功了，client 有没有重连成功还需验证。

3.x 因为个别 api 不兼容 4，不想再改回去了。。

**Comment by musicode** [comment]
![image](https://user-images.githubusercontent.com/2732303/34369196-e8a68b76-eaf4-11e7-896e-be0ff7598b1d.png)
从这看 client 也重连成功了，那就非常奇怪了，client 为啥不在会话中呢

**Comment by musicode** [comment]
![image](https://user-images.githubusercontent.com/2732303/34369580-c573c0ee-eaf7-11e7-9745-ce56a5fd7e78.png)
重连之后我去拉最新的会话列表，红框里的是遍历拉到的会话，然后再异步打开每个会话，报错了

**Comment by musicode** [comment]
@leeyeh 是库的 bug 还是我的调用方式有问题呢？

**Comment by leeyeh** [comment]
我发现了一个可能的问题，请稍等我在调查一下。

**Comment by leeyeh** [comment]
已发布 v4.0.0-beta.1 修复了这个问题，非常抱歉我们的 Bug 给您带来的不便。

**Comment by musicode** [comment]
好的，多谢支持啦
