### ISSUE TITLE
npm install leancloud-realtime-plugin-webrtc 之后没有dist目录导致不能import

### ISSUE THREAD

**Issue by LabiKyo** [leancloud/js-realtime-sdk#423]
leancloud-realtime-plugin-webrtc@1.0.0-beta.2

$ ls node_modules/leancloud-realtime-plugin-webrtc
CHANGELOG.md package.json src

**Comment by leeyeh** [comment]
fixed in leancloud-realtime-plugin-webrtc@1.0.0-beta.3
