### ISSUE TITLE
打开room的时候经常会报 Error: CONVERSATION_LOG_REJECTED

### ISSUE THREAD

**Issue by xgzl87** [leancloud/js-realtime-sdk#426]
打开room的时候经常会报 Error: CONVERSATION_LOG_REJECTED
什么意思啊

**Comment by leeyeh** [comment]
4312	CONVERSATION_LOG_REJECTED	拉取对话消息记录被拒绝，当前用户不在对话中

https://leancloud.cn/docs/realtime_v2.html#云端错误码说明

**Comment by xgzl87** [comment]
谢谢，奇怪，明明在对话中的啊，我再查下

**Comment by xgzl87** [comment]
确实不在这个会话了，可是imClient.getQuery()为什么能取到这个会话呢，很神奇

**Comment by xgzl87** [comment]
确实不在这个会话了，可是imClient.getQuery()为什么能取到这个会话呢，很神奇

**Comment by leeyeh** [comment]
是说 imClient.getQuery() 什么条件都不加能拿到这个会话？有没有可能是在 query 之后被移出会话了。如果确认还能 query 到的话请提供下 appId，clientId 与 conversationId 我们查一下。

**Comment by xgzl87** [comment]
可以私信给你吗?

**Comment by leeyeh** [comment]
yli@leancloud.rocks

**Comment by xgzl87** [comment]
你好，请问你复现了吗？我这边还是能复现，有点在这个会话的反而取不到，很奇怪。

**Comment by xgzl87** [comment]
你好，请问你复现了吗？我这边还是能复现，有点在这个会话的反而取不到，很奇怪。

**Comment by lijia321** [comment]
我也出现这个问题了
