### ISSUE TITLE
升级 protobuf.js to version 6

### ISSUE THREAD

**Issue by leeyeh** [leancloud/js-realtime-sdk#471]
v6 使用了基于 codegen 的反射，能够提供 SDK 的性能时。并且包大小也有明显减少。

Non-breaking，但是由于 v6 完全重写了，在兼容性上会有潜在的风险，因此是个 major change。

**Comment by sdjcw** [comment]
性能是否会有影响？

**Comment by leeyeh** [comment]
According to https://github.com/dcodeIO/protobuf.js#performance，没啥影响。

**Comment by leeyeh** [comment]
暂时不做，维持在 v5。

升级的出发点是包大小与加载性能。升级到 protobufjs@6 之后，包大小有小幅降低，加载时间有小幅降低（可能归功于包大小的降低），但是无法支持小程序（小程序不允许动态生成代码）。

另一个思路是不用 protobuf，回退到 json，包大小与加载性能确实都有大幅的改善，也没有兼容性的问题，但是不使用 protobuf 可能会导致突然有大户的情况下 server 带宽压力大。因此这个方案也不合适。

一些测试结果：

方案|包大小（kB）|初始化耗时（ms）|支持小程序
:-:|:-:|:-:|:-:
protobufjs v5|227|~170|Y
protobufjs v6|205|~170|N
json|135|~80|Y
