### ISSUE TITLE
获取已有 room 的回调参数应该就是这个 room

### ISSUE THREAD

**Issue by wangxiao** [leancloud/js-realtime-sdk#49]
感谢 @liuyanghejerry  的建议。

我会考虑：
* 每个回调中的 this，是否应该就是这个 roomObject；
* 回调的参数是否可以获得 roomObject；

**Comment by liuyanghejerry** [comment]
建议使用第二种方案，因为给回调绑定this，将会影响开发者自己所提供的函数中已经绑定的this（开发者将无法直接使用一个“方法”来作为回调）。

**Comment by wangxiao** [comment]
https://github.com/leancloud/js-realtime-sdk/pull/61
