### ISSUE TITLE
统一异常处理

### ISSUE THREAD

**Issue by leeyeh** [leancloud/js-realtime-sdk#533]
目前，由于实现的时候没有特别注意，SDK throw 异常有同步与异步两种方式，甚至不同 API 抛出同一个异常都有可能是通过不同的方式，比如，当网络断开时：

```javascript
try {
  conversation.send(message);
} catch (error) {
  // hanlde `Connection unavailable` error
}

conversation.add(members).catch(error => {
  // hanlde `Connection unavailable` error
});
```

对于所有异步的 API，都应该统一使用异步的方式抛异常。目前考虑的是使用 async 声明语法来包装所有异步的 API。

由于异常处理方式会变，这将是一个 breaking change。

**Comment by aisk** [comment]
如果只有 try / catch 和 promise 两种异常的话，用户统一都是用 async / await 调用，是不是处理方式就统一了？

**Comment by leeyeh** [comment]
是的，但你不能假设用户使用 async / await 啊。

**Comment by aisk** [comment]
那如果使用 async 声明来包装所有异步 API，如果使用者不使用 async / await，拿到的结果依然是个 Promise，还是需要使用 promise 的 API。

**Comment by leeyeh** [comment]
是的，但是就不会出现前面这种情况了。

**Comment by leeyeh** [comment]
closed by #557
