### ISSUE TITLE
demo中引用的 uuid/v4 在pack时报错

### ISSUE THREAD

**Issue by tearsofphoenix** [leancloud/js-realtime-sdk#535]
直接运行两个demo例子，都会报`Yb.v4() is not a function`的错误，是因为
`import uuid from 'uuid/v4'`中的uuid已经是函数了，不应在调用的时候再
用`uuid.v4()`，而是`uuid()`。

**Comment by leeyeh** [comment]
是的，谢谢报告，已经修复，还没有合并到 master。

**Comment by leeyeh** [comment]
已恢复。
