### ISSUE TITLE
unreadmessagescountupdate 事件没有被实施？

### ISSUE THREAD

**Issue by dangyuluo** [leancloud/js-realtime-sdk#539]
我看API文档里说`unreadmessagescountupdate`事件是`unreadmessages`事件的升级版，但是搜索3.3.4 release中却没有找到`unreadmessagescountupdate`关键词。

而且搜索源码里也没有该关键词。请问是还没有实施么？

**Comment by leeyeh** [comment]
since 3.4.0，还没有正式发布。

可以使用 `npm i leancloud/js-realtime-sdk#dist` 安装 master 上的代码。

**Comment by dangyuluo** [comment]
@leeyeh 哦这样子，还真没有看到since 3.4.0，看文档不仔细。

**Comment by leeyeh** [comment]
我们的文档反映的是 master，很抱歉给您造成了困扰。我们一直想给文档加上版本切换的功能，但是优先级不高所以暂时搁置了。
