### ISSUE TITLE
考虑 SDK 是否需要默认防止 XSS

### ISSUE THREAD

**Issue by wangxiao** [leancloud/js-realtime-sdk#54]
@killme2008 @sunng87 @jwfing 
实时聊天 SDK 使用过程中发现很多用户试了 XSS，如果是一般的小白用户可能就会忽略这个问题。
所以，是否 SDK 层面直接把 XSS 过滤默认做了？
如果用户有不做的需求，那我们有个配置，可以不做 XSS 转义，但是默认 SDK 层面是做 XSS 防御的。

**Comment by killme2008** [comment]
可以增加一个选项，例如 encodeUserInput option之类。

**Comment by sunng87** [comment]
我觉得不用，有点超出库的范围了。XSS 是个 html 层面的事物，我们的库是个通信层面的库。我们在demo和未来的 UI 组件上可以做这个功能。现在我们连接上传输的内容不完全是最终会放在页面上的内容，替换<这些可能导致消息内容甚至格式变化。成熟的用户使用模版引擎的时候，这件事会在模版引擎层面做掉，如果我们在通信库层面做了，内容会被二次转义。

**Comment by wangxiao** [comment]
我很担心很多用户并不知道在 Web 上面要做 HTML 转义防止 XSS，同意晓丹的建议，我增加一个选项。但是默认是做 HTML 转义的，这样也能够说下我们的 SDK 是注重安全的。也能够支持宁姐的用法吧？成熟的用户知道要去关掉。

**Comment by killme2008** [comment]
我个人觉的这个选项应该是默认关闭的，作为高级功能提供， js sdk 的文档需要增加一个单独的安全章节说明。

在 2015年3月31日 下午10:24，尼奥 <notifications@github.com>写道：

> 我很担心很多用户并不知道在 Web 上面要做 HTML 转义防止 XSS，同意晓丹的建议，我增加一个选项。但是默认是做 HTML
> 转义的，这样也能够说下我们的 SDK 是注重安全的。也能够支持宁姐的用法吧？成熟的用户知道要去关掉。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/leancloud/js-realtime-sdk/issues/54#issuecomment-88107947>
> .
>



-- 
庄晓丹
Email:        killme2008@gmail.com xzhuang@avos.com
Site:           http://fnil.net
Twitter:      @killme2008

**Comment by wangxiao** [comment]
加一个不停 XSS Demo 的用户进来讨论。。。 @zswang

**Comment by wangxiao** [comment]
我主要是考虑场景：

用户会在 Web 端使用，如果这样那他一定会做 XSS 防御，不管这个防御是在哪，他一定会去做。
所以感觉 SDK 默认防止 XSS 更好些，返回给他干净的字符串，用户可以通过配置不开启此功能。

**Comment by zswang** [comment]
不需要吧，你怎么知道哪个 json 是用来渲染的？不做渲染的 json 你编码了。。。这不是又一个坑。

**Comment by wangxiao** [comment]
一般不会有用户传递纯 HTML 吧？如果需要这样用，那就需要手工关掉是不是更好些？

**Comment by wangxiao** [comment]
最后支持 HTML 转义，防止 XSS，但默认不开启。
https://github.com/wangxiao/js-realtime-sdk/commit/15eff2bd0d5ef75240d340b890ec4d5a85daa33d
