### ISSUE TITLE
关于conversation query时未读消息数目更新的问题。

### ISSUE THREAD

**Issue by dangyuluo** [leancloud/js-realtime-sdk#540]
我最近在做聊天列表，需要首先查询出登录用户所参与的所有会话，并显示有几条未读消息。我发现leancloud在处理的时候有着么一个逻辑，我无法理解。

首先`conversation query`和服务器通讯是需要时间的，假设0s开始查询，耗时1秒。如果在0-1s内，`IMClient`收到了`unreadmessages` event, 那么`conversation query`查询的结果中，`unreadMessagesCount`结果是正确的。

但是如果因为网络波动问题，`IMClient`在1.5s才收到了`unreadmessages` event,那么在1s时`conversation query`返回的结果中`unreadMessagesCount`（在1s `unreadmessages` 还未到来时）就一定是0，当然一旦`unreadmessages`到来了，这个值就又正确了。

是否可以理解为`conversation query`返回的结果中`unreadMessagesCount`是由`unreadmessages`事件更新的？为什么不能在`conversation query`结果中直接包含未读消息数目呢？

谢谢。

**Comment by leeyeh** [comment]
你的理解是正确的，准确的说，SDK 返回的同一个 id 的 Conversation 都会是同一个实例。所以尽管 query 与 `unreadmessages` event 是有可能出现不同的先后顺序的，SDK 会保证最终 conversation 的 `unreadMessagesCount` 会被更新到最新值。

query 与 未读消息数更新通知是两个独立的功能，在设计上我们不希望这两个功能有耦合。

此外，在未读消息方面，我们即将在 v3.4 中 ship 一些新的功能与优化，还请关注我们的发布记录与文档更新。

**Comment by dangyuluo** [comment]
@leeyeh 好的，了解。我现在的解决方案是在`unreadmessages`到达的时候手动去更新DOM里的未读消息badge显示。
那就等你们v3.4啦，辛苦。

**Comment by leeyeh** [comment]
v3.4.0 published.
