### ISSUE TITLE
IMClient#unreadmessagescountupdate事件与message事件冲突？

### ISSUE THREAD

**Issue by left4taco** [leancloud/js-realtime-sdk#546]
在升级至3.4.0版本的过程中，我发现了一处问题。
在上一个版本的js sdk中，我监听IMClient上派发的`message`事件来更新对话列表页的显示，代码如下：
```javascript
client.on('message', function(message, conversation) { //首先根据conversationid找出列表内是否有该会话。
    console.log('Message received: ' + message.text, '. Conversation:', conversation);
    i = v.list_sequence.indexOf(conversation.id);
    if(i == -1){//没有找到该会话
    }else{
        delete v.list[i]
        delete v.list_sequence[i]
    }
    v.add_new_conversation(conversation)//将该会话添加到最前端
});
```

但是在升级至3.4.0后，我添加了`unreadmessagescountupdate`事件的监听。非常神奇的是，在我监听`unreadmessagescountupdate`后，`message`事件不派发了！
如果我移除`unreadmessagescountupdate`的监听，`message`事件则恢复正常。

请问这是正常情况么？或者是bug？

**Comment by leeyeh** [comment]
http://jsplay.avosapps.com/jip/edit?js,console

我试了看起来没有问题，你能否提供一个可以复现的场景呢。

尽管如此，我发现当收到线消息的时候，`unreadmessagescountupdate` 事件 payload 给的是 `conversation` 而不是 `[conversation]`，这是一个 bug，虽然应该与你遇到的问题无关。

**Comment by dangyuluo** [comment]
@leeyeh 我的应用只能在微信里打开，而且对外不方便调试，我尽量提供个场景试试吧。

你说的第二个问题还好，不算bug。在`unreadmessagescountupdate`回调函数中判断一下就可以了。
