### ISSUE TITLE
ionic2 leancloud-realtime realtime.d.ts 报错

### ISSUE THREAD

**Issue by flyhuang** [leancloud/js-realtime-sdk#555]
leancloud realtime 版本: 3.5.1

报错内容如下:
[11:15:06]  typescript: node_modules/leancloud-realtime/realtime.d.ts, line: 93 
            A 'declare' modifier cannot be used in an already ambient context. 

      L92:    declare type MessagePointer = Message | {id: string, timestamp: Date|number};
      L94:    export interface AVMessage {

[11:15:06]  typescript: node_modules/leancloud-realtime/realtime.d.ts, line: 119 
            An accessor cannot be declared in an ambient context. 

     L118:  get title(): string;
     L119:  type: number;
     L120:  getAttributes(): {};

**Comment by leeyeh** [comment]
fixed in v3.5.2
