### ISSUE TITLE
请问如何处理未读消息？

### ISSUE THREAD

**Issue by hellolibo** [leancloud/js-realtime-sdk#56]
如题

**Comment by wangxiao** [comment]
首先读或者未读是使用者的逻辑，实时通信本身不做处理。

但是实时通信底层会对收到还是没收到消息做处理，默认会推送最近 10 条没有收到过的消息。

**Comment by hellolibo** [comment]
你这里推送的10条是针room吗？

**Comment by wangxiao** [comment]
对的，针对 Room，同时会区分 ClientId 。
