### ISSUE TITLE
web端的聊天室，数据跟iOS端数据不同步

### ISSUE THREAD

**Issue by lanqy** [leancloud/js-realtime-sdk#565]
web端建了一个聊天室（暂态的），iOS 用的也是同一个 leancloud 账号的 app，现在发现在web端发的聊天，不能在 iOS 端显示，同样在 iOS 端发信息，web 端的聊天室也收不到来自 iOS 端的消息,看 leancloud 后台，数据插入是成功的。

**Comment by lanqy** [comment]
@leeyeh 能否帮忙看一下

**Comment by leeyeh** [comment]
请提供下 appId 的前 7 位，收不到消息的 conversationId 与 clientId。

**Comment by lanqy** [comment]
@leeyeh 
appId : UPGg8RN
conversationId : 5979ec35da2f6000615d4962

clientId 这个是根据用户登录动态生成的，也就是登录用户的ID，下面的截图代码片段 : 
![qq 20170825111911](https://user-images.githubusercontent.com/192915/29698329-4792185a-8987-11e7-86b5-d8188640e282.png)

**Comment by leeyeh** [comment]
5979ec35da2f6000615d4962

这个对话是个暂态对话（聊天室），必须要主动加入才能收发消息，并且其他客户端只有同时在线并在这个对话里才能收到消息。

**Comment by lanqy** [comment]
不太明白，主动加入指的是？

**Comment by leeyeh** [comment]
加入是指 join。对于暂态对话，离线之后就会自动退出，并且也不会收到离线消息推送。所以只有同时在线时再能互相收到消息。

**Comment by lanqy** [comment]
意思要手动去调一下 join 吗？

**Comment by leeyeh** [comment]
是的。

**Comment by lanqy** [comment]
已经排查出问题了，我这边代码的问题，写错 leancloud_room 的值。感谢 @leeyeh 的耐心回复。
