### ISSUE TITLE
js-realtime-sdk doesn't work in electron

### ISSUE THREAD

**Issue by flyhuang** [leancloud/js-realtime-sdk#566]
我尝试在electron内使用leancloud去开发. 发生了如下异常
<img width="617" alt="screen shot 2017-08-29 at 4 56 26 pm" src="https://user-images.githubusercontent.com/1689430/29813000-20ad4f46-8cdb-11e7-8437-ae88475da6c4.png">

demo地址:
https://github.com/flyhuang/electron-quick-start

**Comment by leeyeh** [comment]
fixed in v3.5.6
