### ISSUE TITLE
微信小程序里socket能用protocolBuffer吗？

### ISSUE THREAD

**Issue by l3ve** [leancloud/js-realtime-sdk#568]
我们的小程序里websocket打算用protocolBuffer，不知道这个sdk能兼容不

**Comment by leeyeh** [comment]
请问你是想要在你的业务中通过我们的实时通讯服务发送二进制类型的消息对吗？

**Comment by l3ve** [comment]
是的

**Comment by leeyeh** [comment]
当前的 SDK 暂时只支持可以序列化为文本类型的消息，下一个版本会支持二进制消息，预计本月内发布。

**Comment by leeyeh** [comment]
supported in v4.0.0-alpha.2
