### ISSUE TITLE
rt 的 "message" 事件的疑问？

### ISSUE THREAD

**Issue by hellolibo** [leancloud/js-realtime-sdk#57]
文档中提到  “...收到的消息是当前客户端（clientId）存在的 Room 中的信息....”  这是不是意味着当初始化完成后，我必须为我所有的好友都建立room，不然，我是不是不能提收到他发来信息。

**Comment by hellolibo** [comment]
a 和 b 同时创建一个包括自己去对方的room  ，他们在leancloud其实是一个。

**Comment by wangxiao** [comment]
不是，这是两个房间，就是我们不会做房间除重。

**Comment by hellolibo** [comment]
那怎么接收到别人创建的room的消息，如果我在里面的话，使用rt.query吗？

**Comment by wangxiao** [comment]
有对应的事件，请参考文档。

```javascript
// 监听创建 Room
realtimeObject.on('create', function() {
});

// 监听所有 Room 中的消息
realtimeObject.on('message', function() {
});

```

**Comment by hellolibo** [comment]
ok, 是我理解错了。
