### ISSUE TITLE
频繁超时

### ISSUE THREAD

**Issue by musicode** [leancloud/js-realtime-sdk#576]
我用的免费试用版，超时十分频繁，不知道是免费版问题还是这个库有 bug 呢

![image](https://user-images.githubusercontent.com/2732303/31536617-efbf959e-afc4-11e7-9859-d380a2575046.png)

**Comment by leeyeh** [comment]
https://leancloud.cn/docs/realtime_v2.html#限制

>对于客户端主动发起的操作会按照操作类型限制其频率。发消息操作限制为 每分钟 60 次，历史消息查询操作限制为 每分钟 120 次，其他类型操作包括加入对话、离开对话、登录服务、退出服务等均限制为 每分钟 30 次。当调用超过限制时，云端会拒绝响应这些超限的操作，这样如果操作本由 SDK 发起则表现为不会走回调。

**Comment by musicode** [comment]
我这本地调试环境，经常报超时错误，我发誓没有一个接口一分钟调几十次或者上百次，就是正常的操作，这个样子我都不知道怎么往下调试了。。

**Comment by musicode** [comment]
@leeyeh 方便告知如何才能避免频繁超时么，实在是报的太多了，而且在我本地调试就这么报，到了产品环境那还得了。。

**Comment by leeyeh** [comment]
你可以试一下在控制台运行 `localStorage.debug="LC:Connection"` 打开调试日志，刷新页面后再进行操作可以看到命令发送的频率。

**Comment by musicode** [comment]
react native 环境可以这样用么？

**Comment by musicode** [comment]
@leeyeh 

我还有两个问题

1. 最新版本没发到 npm
2. 我有个场景可能会产生这个问题，比如某个用户有100个会话，第一次初始化时，我去拉取这100个会话列表，然后再依次 `conversation.open()`，这里确实有可能频繁调用，但也没办法啊，这是必须做的操作，其他的地方，我确定没有这么调过

**Comment by musicode** [comment]
@leeyeh 比较着急，有空辛苦帮忙看下哈

**Comment by musicode** [comment]
![image](https://user-images.githubusercontent.com/2732303/35904328-ad8dea30-0c1d-11e8-9194-07552dbc0ca4.png)
当没有超时报错时，一切正常，一旦有了超时，好多都挂了。。

**Comment by musicode** [comment]
@leeyeh 还需要我提供什么信息帮助调试吗

**Comment by leeyeh** [comment]
这是浏览器吗？看起来是 React Native？这里能看到 6 个请求超时了，请问 SDK 的版本是多少？

**Comment by musicode** [comment]
是 react native
```
"leancloud-installation": "^2.0.1",
"leancloud-realtime": "^4.0.0-beta.3",
"leancloud-storage": "^3.4.2",
```

**Comment by leeyeh** [comment]
哦，我没有看到上面的回复。你说到「初始化的时候会调用 100 次 conversation.open()（你说的是
 join() 吗?）」这里肯定是会超过限制的。为什么要这么做呢？

**Comment by musicode** [comment]
刚才说的场景如下：

```
getConversationList().then(list => {
    list.forEach(conversation => {
        conversation.open()
        // 因为 conversation.lastMessage 总是 null
        conversation.getLastMessage()
    })
})
```

初始化时的操作大概就是这样，目前来看，会报 CONVERSATION_API_QUOTA_EXCEEDED 错误，不是超时

后续其他的一次性操作，比如 conversation.save()，经常超时

**Comment by musicode** [comment]
我说的这个遍历场景，有啥好的优化方式吗

**Comment by leeyeh** [comment]
>conversation.open()

conversation 并没有 open 方法啊？

另外为什么要在每次登录的时候立刻加入 100 个对话呢？

**Comment by musicode** [comment]
```
getConversationList().then(list => {
    list.forEach(conversation => {
        client.getConversation(conversation.id, true).then(() => {
            // 因为 conversation.lastMessage 总是 null
            conversation.getLastMessage()
        })
    })
})
```

不是立即加入 100 个会话，是搜索该用户相关的会话，返回的列表比较大，比如有 100 个

**Comment by leeyeh** [comment]
为什么要禁用缓存重新获取一次所有的对话信息呢（getConversation)，以及 getLastMessage 是查询历史消息实现的吗？

**Comment by musicode** [comment]
好的，我试试先去掉缓存，getLastMessage 是查询最后一条历史消息实现的

**Comment by musicode** [comment]
对于第一次获取列表来说，其实是否缓存都不重要吧，都是从服务器读数据？那么后续的超时会是什么原因呢

**Comment by leeyeh** [comment]
不是要去掉缓存，而是在 getList 之后，不要再挨个禁用缓存再 get 一次。

另外不需要查历史消息，在使用 Query getList 的时候使用 这个 API： https://leancloud.github.io/js-realtime-sdk/docs/ConversationQuery.html#withLastMessagesRefreshed

**Comment by musicode** [comment]
目前来看，改成了你说的初始化方式，超时没有了，是不是第一次产生了大量的请求，堵塞导致了超时？

**Comment by leeyeh** [comment]
是这样的。

**Comment by musicode** [comment]
最新版方便发 npm 么

**Comment by leeyeh** [comment]
已发。
