### ISSUE TITLE
[Question] 如何获取message.deliveredAt值？

### ISSUE THREAD

**Issue by sevengo8378** [leancloud/js-realtime-sdk#586]
v3.5.7：
会在conversation上派发receipt事件，回调函数有message参数，可以获取到deliveredAt

v4.0.0:
看到最新版本已经不派发receipt事件，新的机制是在handleReceipt时派发lastdeliveredatupdate事件，然后可以通过conversation.fetchReceiptTimestamps更新conversation.lastDeliveredAt
不知道新版本如何去获取到发出去消息的message.deliveredAt值？

**Comment by leeyeh** [comment]
Message 还是有 deliveredAt 属性的，发出去的消息如果被确认送达，发送方对应的 Message 的 deliveredAt 属性会被更新。

需要特别指出的是，由于消息的送达确认与已读确认都是批量的，因此最后已送达消息时间与最后已读消息时间一样，是 Conversation 上的一个时间戳，并不是每一条消息都会带有 deliveredAt 属性。

**Comment by sevengo8378** [comment]
我的目的是想通过message.deliveredAt - message.timestamp去计算消息从服务器到接收方的延迟，message的deliveredAt确实会被更新，就是不明白更新后发送方可以通过什么方式得到获得通知，请指教
另外想问一下如果要计算延迟怎样一个思路比较好？

**Comment by sevengo8378** [comment]
谢谢分析，理解你们调整的原因了
