### ISSUE TITLE
room 的一些疑惑？

### ISSUE THREAD

**Issue by hellolibo** [leancloud/js-realtime-sdk#59]
当前用户想和另一人对话时需要创建一个room，把自己和那个人一起加入，  聊了些内容后，过一段时间后，用户再次点开这个好友时，为了获取原来聊的内容，就必须要知道之间的room id，不然，又是新建room 了，那不是我还要想办法记录这个roomid?

**Comment by hellolibo** [comment]
demo3里可以让我自己修改roomID, 用的也是rt.conv(id);  请问，你文档里不是写了这个是获取服务器已有的room吗? 我随便输入一个也是可以的嘛？   这意为着是不是roomID我可以按我的规则组合出来用啊？

**Comment by wangxiao** [comment]
对的，设计实时通信的时候考虑的是实时通信与好友关系等逻辑是解耦合的，所以你需要自己存储。
这也是灵活的，因为我们不清楚你的好友逻辑。
你可以使用 LeanCloud 的存储，给每个用户建立一个好友关系，然后他们存储着对应的 roomId 即可。
每次聊天之前获取一下他们是否有 roomId 即可。

**Comment by wangxiao** [comment]
localStorage 只是随便写在 demo 中保持逻辑的，你真正用可以存储在服务器端，可以尝试使用 LeanCloud 的无模式存储。
