### ISSUE TITLE
Demo没法正常运行什么原因

### ISSUE THREAD

**Issue by panhs** [leancloud/js-realtime-sdk#592]
mac系统的chrom浏览器
————————————————————
npm install  &grunt
运行index.html
报错 Uncaught TypeError: AV.Realtime is not a constructor
    at HTMLDivElement.login (test.js:74)

**Comment by panhs** [comment]
npm install leancloud-realtime --save下载会失败提示
44 error Darwin 17.2.0
45 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "leancloud-realtime" "--save"
46 error node v6.11.0
47 error npm  v3.10.10
48 error code ENOSELF
49 error Refusing to install leancloud-realtime as a dependency of itself
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]

**Comment by leeyeh** [comment]
如果你只是想查看 Demo 的效果，可以直接使用在线的版本： https://leancloud.github.io/js-realtime-sdk/demo/simple-chatroom/

>Refusing to install leancloud-realtime as a dependency of itself

多半是因为你在这个项目的目录下试图 install leancloud-realtime 本身。
