### ISSUE TITLE
实时通讯不支持IE10？

### ISSUE THREAD

**Issue by stevieyu** [leancloud/js-realtime-sdk#594]
浏览器版本: ie10
报错内容：SCRIPT5022: 引发了异常但未捕获
加载方式：webpack 打包 import 加载

demo 例子也不能在ie10 运行 https://leancloud.github.io/js-realtime-sdk/demo/simple-chatroom/

**Comment by leeyeh** [comment]
确认目前 leancloud-realtime-plugin-typed-messages 有 IE10 兼容的 bug，我们会尽快修复。

leancloud-realtime 本身没有问题，兼容的运行环境包括 IE10： https://github.com/leancloud/js-realtime-sdk#%E6%94%AF%E6%8C%81%E7%9A%84%E8%BF%90%E8%A1%8C%E7%8E%AF%E5%A2%83

**Comment by stevieyu** [comment]
@leeyeh 什么时候发布版本?

**Comment by leeyeh** [comment]
应该在这周内发布，发布之前可以使用 HEAD 版本：

```bash
npm i leancloud/js-realtime-sdk#dist
```
