### ISSUE TITLE
v4.0.0 createIMClient 在 React Native 中返回 undefined

### ISSUE THREAD

**Issue by musicode** [leancloud/js-realtime-sdk#595]
```js
realtime.createIMClient('xxx').then(function (client) {
    // client 为空了
})
```

**Comment by musicode** [comment]
还发现一个问题，如果 save 的内容比较多，不会触发 then
```js
conversation.set(key, {
  // 这是一个比较大的对象，比如存储了200个用户的简要信息
  // 比较小的对象是正常的，我这实验是超过了一定的大小，就不会触发 then
  userId1: { id: 'xx', name: 'xxx', avatar: 'xxx', gender: 0 },
  userId2: { id: 'xx', name: 'xxx', avatar: 'xxx', gender: 0 },
})
conversation.save().then(function () {
  // 不会触发
})
```

**Comment by musicode** [comment]
@leeyeh 麻烦看看哈

**Comment by musicode** [comment]
@leeyeh 这周能帮忙看看么？我这等这个 bug 的修复..

**Comment by leeyeh** [comment]
1. 请提供精确的版本号。
2. 请先尝试捕获异常： `.catch(function(error) {})`。
3. 如果没有异常，请按照 https://leancloud.cn/docs/sdk_setup-js.html#hash1158081233 打开调试日志然后复现问题后提供一下日志。

**Comment by leeyeh** [comment]
>如果 save 的内容比较多，不会触发 then

Conversation 并不是设计用来存储大量的数据的，如果数据量很大，保存甚至查询 Conversation 都会可能超时。如果有这种需求，可以使用存储服务将这些数据存到另一张表里。

**Comment by musicode** [comment]
1. v4.0.0-rc.0
2. 多大算很大呢？我理解会话里的每个用户都可能往里面存数据，比如是否免打扰，是否置顶，这种存储量基本都是 x 用户数量的，如果超过一定量就存不了，那这个存储岂不是很鸡肋？

**Comment by musicode** [comment]
@leeyeh

**Comment by musicode** [comment]
你发的调试方式是针对 web 的，我这是 rn 的环境，用不了

**Comment by leeyeh** [comment]
因为 Conversation 的属性是所有人都会去获取的，我们建议只在 Conversation 中保存这个 Conversation 本身的属性（比如是否是一个全局置顶的会话），而不应该保存每个成员的设置，比如每个成员是否置顶了该会话。试想一下你每次 query 会话列表都会拿到所有对话中所有成员的设置，这性能该有多差。

对于这种需求，建议使用另一个用户 - 对话中间表，将是否置顶等属性放在这个表里，在需要的时候再去查。

> client 为空了

client 为空指的是 undefined 吗？我们的代码里应该保证了这个 promise 如果成功只可能返回 一个 IMClient。确认没有 catch 到任何异常？这个现象是必现还是有规律复现？

**Comment by musicode** [comment]
当初我选择放进去这一堆用户数据，主要是提升性能，不然每个用户一打开会话都要去取一遍，而且如果有谁更改了数据，也要发消息给会话中的每个用户，让他们再去服务器更新一次数据。

我是从 `4.0.0-beta.4` 升级到最新版试试，我看 breaking changes 也没啥影响我的，就直接升了，client 那就返回 undefined 了，必现的

**Comment by musicode** [comment]
顺便问一下，按照你们的设计理念，conversation 不存每个用户的数据，那么 `conversation.mute()` 和 `conversation.unmute()` 似乎比较鸡肋吧，哪里有全局设置是否免打扰这种需求呢？

**Comment by musicode** [comment]
@leeyeh 会话中的用户数据，假设是用户点击会话列表进入一个会话后，去服务器拉取一次，这种频率其实也还好，毕竟不会出现群里所有人同时拉取的情况，但是，如果碰到有人改动了用户数据，比如某个用户修改了头像，这时会发出一个消息，通知群里其他人该用户改头像了，此时为了保证每个人的数据都是最新的，最好去服务器拉取一次，假设是个 500 人的大群，瞬间并发就是 500。如果不去拉，又怎么保证每个人的数据是最新的呢

**Comment by leeyeh** [comment]
client 为 undefined 的问题我复现了，正在调查。

把用户数据直接放在 Conversation 表中会让 Conversation 相关操作的性能变的很差甚至超时。你可以看一下流行的聊天软件，类似成员头像等信息都是在点到一个详情页之后才去获取的，甚至成员多的话还要再点一下「加载更多」，也是这个原因。

我们之前把 mute 成员的列表放在了 Conversation 表中，这是一个很糟糕的设计，我们在实现之后的管理员等需求的时候已经不再这么做了。

**Comment by musicode** [comment]
总之，在 conversation 存数据是一个普遍需求，只是怎么实现性能比较好，希望官方能给个好用的方式

**Comment by leeyeh** [comment]
>这样收到消息的人才不会查询用户信息就能直接展现

前面说的都没有问题，但是不要「从 conversation 取共享的用户数据」，而是从另一个表里拿这些信息。

>包括我要实现一个人退群，需记录此人接收群的最后一条消息，以便他再次加入该群时，查询历史数据可以有个上限值

也存到另一个中间表里，需要的时候再查。

**Comment by musicode** [comment]
我懂你的意思，问题是性能，就是一个人改动了信息，假设要通知所有人，这时的并发请求，难道服务器都能轻易扛下来么

**Comment by leeyeh** [comment]
我不是很理解为什么一个人改了头像（或者其他他个人的信息）要即时的通知所有这个人所在的对话里的所有成员，有哪个聊天应用是这样做的吗？

**Comment by musicode** [comment]
比如一个会话，A 和 B 一直在聊天，此时 A 去设置里换了头像，再回到会话中，A 的头像不需要更新吗

**Comment by leeyeh** [comment]
你可以在微信的群聊里试一试。

**Comment by musicode** [comment]
你的意思是否是，从列表点击进会话时，请求一次，此时有会话里的所有人的信息，足以正常显示消息，此时如果有人新加入该会话，广播的消息会带上新增用户的信息，此时也不用去请求，如果有人打开用户的详细资料，发现和自己本地存的不一样，就去更新数据库，是这样么

**Comment by leeyeh** [comment]
你自己看自己的头像当然是最新的，但群里其他人改了是不会即时通知给你的。

https://github.com/leancloud/js-realtime-sdk/blob/master/demo/simple-chatroom/test.js#L227-L249

这里有一个例子，通过 id 换 username 展示的。

**Comment by musicode** [comment]
你这个例子，假设是个500人的大群，开始没任何消息，突然有人发了一条，剩下499个人要显示这条消息，必须先获取发送人的信息，于是并发499出去了。。。

**Comment by leeyeh** [comment]
首先群里不会所有人都在线，只有在线收到了消息的成员会需要去 fetch，甚至就算是在线的成员如果我当前没有打开这个对话，也没有必要去请求这个人的头像。另外这里的 user 是有缓存的，如果你已经有这个 user 的信息了那么是不需要再 fetch 的。

这只是一个非常基础的例子，实际如果要处理 500 人群，那么这里的很多流程必须是要优化的，比如对热点数据引入 LeanCache 等。

这个问题的结论是这样的，Conversation 会在很多地方 fetch，不应该在 Conversation 表中保存大量的数据（尤其是 * 成员数这一数量级的信息）。如果报错了大量的数据，可能会导致很多与对话相关的操作超时。建议将这些数据从 Conversation 表中移到另一个相关的表中。没有即可以在 Conversation 表中保存大量数据又保证性能的方案。

**Comment by musicode** [comment]
知道了，谢谢

**Comment by musicode** [comment]
RN 版本修复了辛苦发一版哈

**Comment by leeyeh** [comment]
恩，先保持这个 issue 打开了。

**Comment by leeyeh** [comment]
给 React Native 提了一个 bug：

https://github.com/facebook/react-native/issues/19490

**Comment by musicode** [comment]
看来短期是升不了了。。

**Comment by musicode** [comment]
@leeyeh 还有一个问题，打开会话的设置页，通常会展现所有人的头像，但是 conversation.members 只是用户的 id，那么是否意味着要请求一次服务器，批量获取所有人的简要信息，这个请求的数据量也是很大的

**Comment by musicode** [comment]
我觉得用户名称头像这种都还是好解决的，更蛋疼的是每个用户的设置，比如是否置顶，这种信息是获取到会话列表之后就需要立刻获取的，因为展现会话列表需要这些信息，我想了解的是，IM 在行业应用这么多年，难道没有通用解决方案么？ @leeyeh

**Comment by leeyeh** [comment]
用户置顶了哪些对话只是用户相关的，直接在用户的存储里存他置顶了哪些对话就可以了。有一些用户对话相关的属性，比如用户的群昵称，可以在一个按照用户 - 对话索引的表中存。

**Comment by musicode** [comment]
那不如搞个 user -> conversation 的关联表，用户所有的设置都写到这张表里得了

**Comment by musicode** [comment]
4.0.1 修复了这个问题么？

**Comment by leeyeh** [comment]
是的，不等 React Native 了，

**Comment by musicode** [comment]
顺便问下，商用版可以只用IM和推送么？其他服务我不需要，我看现在是打包在一起卖的是么

**Comment by leeyeh** [comment]
当然可以。您可以在我们官网联系一下售前咨询，我们就不在这里讨论了。

**Comment by musicode** [comment]
@leeyeh 问个推送的问题，因为我之前集成了信鸽推送，所以如果要推送 leancloud 的离线消息，是不是只能通过 leancloud 的云函数监听收到消息的事件，然后调信鸽的方法发推送啊

**Comment by leeyeh** [comment]
可以在 [_receiversOffline](https://leancloud.cn/docs/realtime_v2.html#hash90949420) hook 中调用第三方的推送服务。

另外，一般的技术咨询请通过论坛或工单途径，issue 只处理 bug 反馈，谢谢合作。

**Comment by musicode** [comment]
好的，谢谢告知，下次记得了
