### ISSUE TITLE
IMClient 监听一次‘message’ 回调函数触发三次

### ISSUE THREAD

**Issue by lijia321** [leancloud/js-realtime-sdk#613]
我用的16.8版本react  监听一次 Event.MESSAGE  接受消息触发回调三次每一次的lastMessage不同  监听的Event.INVITED 回调触发一次 
![image](https://user-images.githubusercontent.com/27719080/63480733-8e820d80-c4c5-11e9-8042-dc57f0cb5beb.png)

**Comment by leeyeh** [comment]
听起来在监听之后收到了三条消息，似乎并没有什么问题，你可以打印 msg 来确认一下。

**Comment by lijia321** [comment]
打印每一次的 lastMessage 不同 
![image](https://user-images.githubusercontent.com/27719080/63484240-8b8d1a00-c4d1-11e9-9aef-2ab76644cc05.png)
![image](https://user-images.githubusercontent.com/27719080/63484258-93e55500-c4d1-11e9-9afd-9d95beaa9460.png)
![image](https://user-images.githubusercontent.com/27719080/63484263-99db3600-c4d1-11e9-895c-acaa682849b6.png)
我想知道这代表什么

**Comment by leeyeh** [comment]
代表你收到了三条不同的消息。
