### ISSUE TITLE
Error: App [qQS3pFiLfOx5YGlokrphiKqg-9Nh9j0Va] is aleady initialized.

### ISSUE THREAD

**Issue by leoyb** [leancloud/js-realtime-sdk#638]
![image](https://user-images.githubusercontent.com/10185166/86309034-4c7d3880-bc4d-11ea-8b6c-1b5f31fea655.png)

调用：new Realtime({ appId, appKey, server: serverURLs })，提示以上错误

"leancloud-realtime": "^5.0.0-beta.3",

**Comment by leeyeh** [comment]
https://github.com/leancloud/js-realtime-sdk/releases/tag/v5.0.0-rc.3

>不再允许使用相同的 appId 初始化多个 Realtime 实例。该用法一般是对 SDK 的误用，容易导致连接数异常增长。对于大多数用户，该变动不会对应用带来任何影响。

请问是不是多次初始化同一个应用了呢？

**Comment by leoyb** [comment]
嗯嗯，我检查下，开始我用低版本的 yarn 编译代码时没有报这个错误，后来我升级了 yarn 到 1.16.0，就提示了这个错误。

**Comment by leoyb** [comment]
如何判断应用是否已经初始化？

**Comment by leeyeh** [comment]
请问你的代码里初始化 Realtime 是写在哪里的呢？

一般来讲，Realtime 应该会在 Web App 初始化的时候的时候（静态的）初始化，WebApp 一般也只会初始化一次。
