### ISSUE TITLE
项目运行不了是为什么呢

### ISSUE THREAD

**Issue by langlangl** [leancloud/js-realtime-sdk#648]
执行  npm run  test:browser-local

报 如下错误
![image](https://user-images.githubusercontent.com/50538948/99621668-751e9700-2a63-11eb-950e-8fd0406eda8b.png)
![image](https://user-images.githubusercontent.com/50538948/99621710-8e274800-2a63-11eb-87b4-3f488f2c613b.png)
怎么解决呢

**Comment by langlangl** [comment]
WARN: 'priority option is ignored as the conversation is not transient.'
.
WARN: 'priority option is ignored as the conversation is not transient.'
............
WARN: 'Middleware[ErrorPlugin:beforeMessageParse] param/return types not match. It returns a Number while a Object expected.'
WARN: 'Middleware[ErrorPlugin:beforeMessageParse] param/return types not match. It returns undefined while a Object expected.'
.
Chrome 86.0.4240 (Mac OS X 10.14.6): Executed 166 of 166 (1 FAILED) (32.049 secs / 24.224 secs)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leancloud-realtime@5.0.0-rc.3 test:browser-local: `npm run build:test && karma start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leancloud-realtime@5.0.0-rc.3 test:browser-local script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2020-11-19T04_19_26_380Z-debug.log

**Comment by langlangl** [comment]
19 11 2020 12:18:53.041:INFO [Chrome 86.0.4240 (Mac OS X 10.14.6)]: Connected on socket x6sioQzbouiykcT7AAAA with id 78834390
..................
Chrome 86.0.4240 (Mac OS X 10.14.6) Realtime _register/_deregister clients FAILED
        Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
....19 11 2020 12:18:56.799:WARN [web-server]: 404: /base/test/browser/index.js.map

**Comment by sdjdd** [comment]
看样子是某个测试用例超时了。
发布的时候会保证通过所有的测试用例，不会影响您在项目中正常使用的。
