### ISSUE TITLE
Warning Using browser-only version of superagent in non-browser environment

### ISSUE THREAD

**Issue by stevendong** [leancloud/js-realtime-sdk#673]
在快应用中调用conversation.send(new Textmessage('hello wolrd')).then()会报这个问题，是还没兼容快应用吗？

**Comment by sdjdd** [comment]
是否设置了快应用的 Adapters ？
> https://leancloud.cn/docs/sdk_setup-js.html#hash24377919

**Comment by stevendong** [comment]
> 是否设置了快应用的 Adapters ？
> 
> > https://leancloud.cn/docs/sdk_setup-js.html#hash24377919

有设置的，初始化登录都没有问题，发消息就报出这个问题了，猜测是new Textmesage 的时候发生的

**Comment by sdjdd** [comment]
可以贴一下导入 SDK 的代码吗。

**Comment by stevendong** [comment]
https://rpk.quickapp.cn/s/28f10ab392d5e46719f6252a8e87d258
你可以通过这个链接打开这个快应用sample，基本按照官网文档，就是跑不起来的

**Comment by sdjdd** [comment]
> Warning Using browser-only version of superagent in non-browser environment

这个错误的原因是设置了浏览器使用的 adapters 。我导入了你分享的代码，因为没有真机，就用开发工具本地测试了一下，没有复现上述问题。

我觉得也有可能是开发工具的问题，可以重新安装依赖试一试。

**Comment by stevendong** [comment]
因为开发工具里面的预览是浏览器环境，和真机差异还有较大不同，所以应该以真机的表现为准，这个警告就是真机抛出来的，你可以看app.ux里的代码，就是完全按照官网文档写的，甚至连window这种对象的都有问题，在看了adapters快应用的代码和realtime的代码，我发现两点问题：
1、adapters没有看到对window对象的模拟；
2、realtime的引用目录里也没有针对快应用的js，但是有node和小程序的。
所以我理解应该是没有完全适配快应用，不知道对不对？

**Comment by sdjdd** [comment]
1. 没有对 window 对象的模拟是因为快应用 Adapters 不是提供一个兼容 HTML5 的环境，而是将快应用独有的接口包装成统一的接口。

2. Node 作为常用平台提供单独的入口，不需要设置 Adapters 。微信小程序的入口文件是 Adapters 机制出现之前的产物。为解决需要为不同平台提供独立的入口文件的问题才创建了 Adapters 机制。

**Comment by stevendong** [comment]
那辛苦再看下吧，按照官网文档，即时通讯的SDK在快应用中确实跑不起来。

**Comment by sdjdd** [comment]
我用云测申请了一台远程主机试了下，发现问题出在 `leancloud-realtime-plugin-typed-messages` 这个包。把 require 这个包的代码删掉，从 `leancloud-realtime/im` 中引入 `TextMessage` 就可以在真机上正常发送文本消息了。

我后续会解决下富媒体消息插件的跨平台兼容性。

**Comment by stevendong** [comment]
好的，感谢~
