### ISSUE TITLE
RealtimeObject.open()出错时如何handle error？

### ISSUE THREAD

**Issue by cnjsstong2** [leancloud/js-realtime-sdk#75]
有时候会出现connection timeout的情况，好像目前没有一个on error的callback？

**Comment by wangxiao** [comment]
open 还真是没对超时进行监控，但是失败会自动重连重试，后续考虑增加一个重试次数和超时的错误暴露。目前你可以手动在外层实现，或者直接 pull request 代码过来。

**Comment by wangxiao** [comment]
目前可以在
rt.on('error', function() {});
里面捕获所有错误信息。

**Comment by wangxiao** [comment]
目前还是推荐监听 reuse 事件，然后自行控制，可以觉得超时之后，自行 close()，然后再自行 open()
