### ISSUE TITLE
js-realtime-sdk 里如何实现单聊

### ISSUE THREAD

**Issue by lentg** [leancloud/js-realtime-sdk#85]
js-realtime-sdk 里如何实现单聊

**Comment by wangxiao** [comment]
请先看文档  https://leancloud.cn/docs/js_realtime.html

**Comment by ds-en-lentg** [comment]
单聊，是不是创建一个只有两个人的room，是这样实现吗？

**Comment by wangxiao** [comment]
是的。

**Comment by ds-en-lentg** [comment]
A新建了一个room，成员有B,在A没说话前，B如何找到A所在的room？

**Comment by ds-en-lentg** [comment]
假如我是Admin，如何找到所有在线的客户，然后给他们发送信息？

**Comment by wangxiao** [comment]
看文档吧，仔细想想，不要没看文档就过来问。
