### ISSUE TITLE
一个聊天室里只有我的信息是为什么？

### ISSUE THREAD

**Issue by hellolibo** [leancloud/js-realtime-sdk#89]
与一方在一个room时聊天，但是重新打开进入这个room时 conv.log返回的信息里只有自己的发的信息是怎么回事？

**Comment by sunng87** [comment]
对方是否发的是 transient 消息？

**Comment by hellolibo** [comment]
不是，我应用里没有用到transient

**Comment by sunng87** [comment]
方便提一个 ticket 附上你的 appid 和 convid 吗，我在后台查一下

**Comment by hellolibo** [comment]
ok

**Comment by hellolibo** [comment]
忽略，程序逻辑问题。
