### ISSUE TITLE
throw的error无法被catch

### ISSUE THREAD

**Issue by cnjsstong2** [leancloud/js-realtime-sdk#96]
https://github.com/leancloud/js-realtime-sdk/blob/master/src/AV.realtime.js#L359

这里的throw貌似无处catch？导致的结果是出错，并且on('error')的callback不被执行。

**Comment by wangxiao** [comment]
确实，throw 会阻止 js 代码继续执行，修复了一个版本。
https://github.com/leancloud/js-realtime-sdk/pull/97

**Comment by wangxiao** [comment]
hi 重新试了下，并没有发生这样的情况，error 是可以被捕获到的。
能够具体调试下？

**Comment by cnjsstong2** [comment]
所有throw出来的error都只能被window.onerror处理啊，这样实用价值很低

**Comment by wangxiao** [comment]
了解你的意思了，会考虑详细做一个错误码的对照表。
